/* Generated By:JavaCC: Do not edit this line. _881Constants.java */
package com.appliedmodels.edifact.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface _881Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ACA = 6;
  /** RegularExpression Id. */
  int ACT = 7;
  /** RegularExpression Id. */
  int ALC = 8;
  /** RegularExpression Id. */
  int ALI = 9;
  /** RegularExpression Id. */
  int API = 10;
  /** RegularExpression Id. */
  int BGM = 11;
  /** RegularExpression Id. */
  int CNT = 12;
  /** RegularExpression Id. */
  int CTA = 13;
  /** RegularExpression Id. */
  int CUX = 14;
  /** RegularExpression Id. */
  int DOC = 15;
  /** RegularExpression Id. */
  int DTM = 16;
  /** RegularExpression Id. */
  int FII = 17;
  /** RegularExpression Id. */
  int FTX = 18;
  /** RegularExpression Id. */
  int GIN = 19;
  /** RegularExpression Id. */
  int GIR = 20;
  /** RegularExpression Id. */
  int IMD = 21;
  /** RegularExpression Id. */
  int LIN = 22;
  /** RegularExpression Id. */
  int LOC = 23;
  /** RegularExpression Id. */
  int MEA = 24;
  /** RegularExpression Id. */
  int NAD = 25;
  /** RegularExpression Id. */
  int PAC = 26;
  /** RegularExpression Id. */
  int PAI = 27;
  /** RegularExpression Id. */
  int PAT = 28;
  /** RegularExpression Id. */
  int PCI = 29;
  /** RegularExpression Id. */
  int PIA = 30;
  /** RegularExpression Id. */
  int PRP = 31;
  /** RegularExpression Id. */
  int QVA = 32;
  /** RegularExpression Id. */
  int RFF = 33;
  /** RegularExpression Id. */
  int SDQ = 34;
  /** RegularExpression Id. */
  int SID = 35;
  /** RegularExpression Id. */
  int TDT = 36;
  /** RegularExpression Id. */
  int TMA = 37;
  /** RegularExpression Id. */
  int TOD = 38;
  /** RegularExpression Id. */
  int TRI = 39;
  /** RegularExpression Id. */
  int TXS = 40;
  /** RegularExpression Id. */
  int TXT = 41;
  /** RegularExpression Id. */
  int UNB = 42;
  /** RegularExpression Id. */
  int UNE = 43;
  /** RegularExpression Id. */
  int UNG = 44;
  /** RegularExpression Id. */
  int UNH = 45;
  /** RegularExpression Id. */
  int UNS = 46;
  /** RegularExpression Id. */
  int UNT = 47;
  /** RegularExpression Id. */
  int UNZ = 48;
  /** RegularExpression Id. */
  int VAL = 49;
  /** RegularExpression Id. */
  int DATA = 50;
  /** RegularExpression Id. */
  int NUMBER = 51;
  /** RegularExpression Id. */
  int SEGTERM = 52;
  /** RegularExpression Id. */
  int DATASEP = 53;
  /** RegularExpression Id. */
  int COMPDATASEP = 54;
  /** RegularExpression Id. */
  int REPEATSEP = 55;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"ACA\"",
    "\"ACT\"",
    "\"ALC\"",
    "\"ALI\"",
    "\"API\"",
    "\"BGM\"",
    "\"CNT\"",
    "\"CTA\"",
    "\"CUX\"",
    "\"DOC\"",
    "\"DTM\"",
    "\"FII\"",
    "\"FTX\"",
    "\"GIN\"",
    "\"GIR\"",
    "\"IMD\"",
    "\"LIN\"",
    "\"LOC\"",
    "\"MEA\"",
    "\"NAD\"",
    "\"PAC\"",
    "\"PAI\"",
    "\"PAT\"",
    "\"PCI\"",
    "\"PIA\"",
    "\"PRP\"",
    "\"QVA\"",
    "\"RFF\"",
    "\"SDQ\"",
    "\"SID\"",
    "\"TDT\"",
    "\"TMA\"",
    "\"TOD\"",
    "\"TRI\"",
    "\"TXS\"",
    "\"TXT\"",
    "\"UNB\"",
    "\"UNE\"",
    "\"UNG\"",
    "\"UNH\"",
    "\"UNS\"",
    "\"UNT\"",
    "\"UNZ\"",
    "\"VAL\"",
    "<DATA>",
    "<NUMBER>",
    "\"\\\'\"",
    "\"+\"",
    "\":\"",
    "\"*\"",
  };

}
