/* Generated By:JavaCC: Do not edit this line. _901Constants.java */
package com.appliedmodels.edifact.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface _901Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ACA = 6;
  /** RegularExpression Id. */
  int ACT = 7;
  /** RegularExpression Id. */
  int ALC = 8;
  /** RegularExpression Id. */
  int ALI = 9;
  /** RegularExpression Id. */
  int API = 10;
  /** RegularExpression Id. */
  int BGM = 11;
  /** RegularExpression Id. */
  int CNT = 12;
  /** RegularExpression Id. */
  int CTA = 13;
  /** RegularExpression Id. */
  int CUX = 14;
  /** RegularExpression Id. */
  int DOC = 15;
  /** RegularExpression Id. */
  int DTM = 16;
  /** RegularExpression Id. */
  int EQA = 17;
  /** RegularExpression Id. */
  int EQF = 18;
  /** RegularExpression Id. */
  int FII = 19;
  /** RegularExpression Id. */
  int FTX = 20;
  /** RegularExpression Id. */
  int GIN = 21;
  /** RegularExpression Id. */
  int GIR = 22;
  /** RegularExpression Id. */
  int HAN = 23;
  /** RegularExpression Id. */
  int IMD = 24;
  /** RegularExpression Id. */
  int LIN = 25;
  /** RegularExpression Id. */
  int LOC = 26;
  /** RegularExpression Id. */
  int LTM = 27;
  /** RegularExpression Id. */
  int MEA = 28;
  /** RegularExpression Id. */
  int NAD = 29;
  /** RegularExpression Id. */
  int PAC = 30;
  /** RegularExpression Id. */
  int PAI = 31;
  /** RegularExpression Id. */
  int PAT = 32;
  /** RegularExpression Id. */
  int PCI = 33;
  /** RegularExpression Id. */
  int PIA = 34;
  /** RegularExpression Id. */
  int PRP = 35;
  /** RegularExpression Id. */
  int QTY = 36;
  /** RegularExpression Id. */
  int QVA = 37;
  /** RegularExpression Id. */
  int RFF = 38;
  /** RegularExpression Id. */
  int SCC = 39;
  /** RegularExpression Id. */
  int SDQ = 40;
  /** RegularExpression Id. */
  int SID = 41;
  /** RegularExpression Id. */
  int TDT = 42;
  /** RegularExpression Id. */
  int TMA = 43;
  /** RegularExpression Id. */
  int TOD = 44;
  /** RegularExpression Id. */
  int TRI = 45;
  /** RegularExpression Id. */
  int TXS = 46;
  /** RegularExpression Id. */
  int UNB = 47;
  /** RegularExpression Id. */
  int UNE = 48;
  /** RegularExpression Id. */
  int UNG = 49;
  /** RegularExpression Id. */
  int UNH = 50;
  /** RegularExpression Id. */
  int UNS = 51;
  /** RegularExpression Id. */
  int UNT = 52;
  /** RegularExpression Id. */
  int UNZ = 53;
  /** RegularExpression Id. */
  int VAL = 54;
  /** RegularExpression Id. */
  int DATA = 55;
  /** RegularExpression Id. */
  int NUMBER = 56;
  /** RegularExpression Id. */
  int SEGTERM = 57;
  /** RegularExpression Id. */
  int DATASEP = 58;
  /** RegularExpression Id. */
  int COMPDATASEP = 59;
  /** RegularExpression Id. */
  int REPEATSEP = 60;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"ACA\"",
    "\"ACT\"",
    "\"ALC\"",
    "\"ALI\"",
    "\"API\"",
    "\"BGM\"",
    "\"CNT\"",
    "\"CTA\"",
    "\"CUX\"",
    "\"DOC\"",
    "\"DTM\"",
    "\"EQA\"",
    "\"EQF\"",
    "\"FII\"",
    "\"FTX\"",
    "\"GIN\"",
    "\"GIR\"",
    "\"HAN\"",
    "\"IMD\"",
    "\"LIN\"",
    "\"LOC\"",
    "\"LTM\"",
    "\"MEA\"",
    "\"NAD\"",
    "\"PAC\"",
    "\"PAI\"",
    "\"PAT\"",
    "\"PCI\"",
    "\"PIA\"",
    "\"PRP\"",
    "\"QTY\"",
    "\"QVA\"",
    "\"RFF\"",
    "\"SCC\"",
    "\"SDQ\"",
    "\"SID\"",
    "\"TDT\"",
    "\"TMA\"",
    "\"TOD\"",
    "\"TRI\"",
    "\"TXS\"",
    "\"UNB\"",
    "\"UNE\"",
    "\"UNG\"",
    "\"UNH\"",
    "\"UNS\"",
    "\"UNT\"",
    "\"UNZ\"",
    "\"VAL\"",
    "<DATA>",
    "<NUMBER>",
    "\"\\\'\"",
    "\"+\"",
    "\":\"",
    "\"*\"",
  };

}
