/* Generated By:JavaCC: Do not edit this line. _902Constants.java */
package com.appliedmodels.edifact.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface _902Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AJT = 6;
  /** RegularExpression Id. */
  int ALC = 7;
  /** RegularExpression Id. */
  int AUT = 8;
  /** RegularExpression Id. */
  int BGM = 9;
  /** RegularExpression Id. */
  int BUS = 10;
  /** RegularExpression Id. */
  int CHD = 11;
  /** RegularExpression Id. */
  int CNT = 12;
  /** RegularExpression Id. */
  int COM = 13;
  /** RegularExpression Id. */
  int CPI = 14;
  /** RegularExpression Id. */
  int CST = 15;
  /** RegularExpression Id. */
  int CTA = 16;
  /** RegularExpression Id. */
  int CUX = 17;
  /** RegularExpression Id. */
  int DCR = 18;
  /** RegularExpression Id. */
  int DGS = 19;
  /** RegularExpression Id. */
  int DIM = 20;
  /** RegularExpression Id. */
  int DLI = 21;
  /** RegularExpression Id. */
  int DMS = 22;
  /** RegularExpression Id. */
  int DOC = 23;
  /** RegularExpression Id. */
  int DTM = 24;
  /** RegularExpression Id. */
  int EQA = 25;
  /** RegularExpression Id. */
  int EQD = 26;
  /** RegularExpression Id. */
  int EQN = 27;
  /** RegularExpression Id. */
  int ERC = 28;
  /** RegularExpression Id. */
  int ERP = 29;
  /** RegularExpression Id. */
  int FCA = 30;
  /** RegularExpression Id. */
  int FII = 31;
  /** RegularExpression Id. */
  int FTX = 32;
  /** RegularExpression Id. */
  int GDS = 33;
  /** RegularExpression Id. */
  int GID = 34;
  /** RegularExpression Id. */
  int GIN = 35;
  /** RegularExpression Id. */
  int GIR = 36;
  /** RegularExpression Id. */
  int GIS = 37;
  /** RegularExpression Id. */
  int GOR = 38;
  /** RegularExpression Id. */
  int HIN = 39;
  /** RegularExpression Id. */
  int IMD = 40;
  /** RegularExpression Id. */
  int INP = 41;
  /** RegularExpression Id. */
  int LIN = 42;
  /** RegularExpression Id. */
  int LOC = 43;
  /** RegularExpression Id. */
  int MEA = 44;
  /** RegularExpression Id. */
  int MOA = 45;
  /** RegularExpression Id. */
  int NAD = 46;
  /** RegularExpression Id. */
  int PAC = 47;
  /** RegularExpression Id. */
  int PAI = 48;
  /** RegularExpression Id. */
  int PAT = 49;
  /** RegularExpression Id. */
  int PCI = 50;
  /** RegularExpression Id. */
  int PIA = 51;
  /** RegularExpression Id. */
  int QVA = 52;
  /** RegularExpression Id. */
  int RFF = 53;
  /** RegularExpression Id. */
  int SEL = 54;
  /** RegularExpression Id. */
  int SGP = 55;
  /** RegularExpression Id. */
  int TAX = 56;
  /** RegularExpression Id. */
  int TCC = 57;
  /** RegularExpression Id. */
  int TDT = 58;
  /** RegularExpression Id. */
  int TMD = 59;
  /** RegularExpression Id. */
  int TMP = 60;
  /** RegularExpression Id. */
  int TOD = 61;
  /** RegularExpression Id. */
  int TPL = 62;
  /** RegularExpression Id. */
  int TSR = 63;
  /** RegularExpression Id. */
  int UNA = 64;
  /** RegularExpression Id. */
  int UNB = 65;
  /** RegularExpression Id. */
  int UNE = 66;
  /** RegularExpression Id. */
  int UNG = 67;
  /** RegularExpression Id. */
  int UNH = 68;
  /** RegularExpression Id. */
  int UNS = 69;
  /** RegularExpression Id. */
  int UNT = 70;
  /** RegularExpression Id. */
  int UNZ = 71;
  /** RegularExpression Id. */
  int VLN = 72;
  /** RegularExpression Id. */
  int DATA = 73;
  /** RegularExpression Id. */
  int NUMBER = 74;
  /** RegularExpression Id. */
  int SEGTERM = 75;
  /** RegularExpression Id. */
  int DATASEP = 76;
  /** RegularExpression Id. */
  int COMPDATASEP = 77;
  /** RegularExpression Id. */
  int REPEATSEP = 78;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"AJT\"",
    "\"ALC\"",
    "\"AUT\"",
    "\"BGM\"",
    "\"BUS\"",
    "\"CHD\"",
    "\"CNT\"",
    "\"COM\"",
    "\"CPI\"",
    "\"CST\"",
    "\"CTA\"",
    "\"CUX\"",
    "\"DCR\"",
    "\"DGS\"",
    "\"DIM\"",
    "\"DLI\"",
    "\"DMS\"",
    "\"DOC\"",
    "\"DTM\"",
    "\"EQA\"",
    "\"EQD\"",
    "\"EQN\"",
    "\"ERC\"",
    "\"ERP\"",
    "\"FCA\"",
    "\"FII\"",
    "\"FTX\"",
    "\"GDS\"",
    "\"GID\"",
    "\"GIN\"",
    "\"GIR\"",
    "\"GIS\"",
    "\"GOR\"",
    "\"HIN\"",
    "\"IMD\"",
    "\"INP\"",
    "\"LIN\"",
    "\"LOC\"",
    "\"MEA\"",
    "\"MOA\"",
    "\"NAD\"",
    "\"PAC\"",
    "\"PAI\"",
    "\"PAT\"",
    "\"PCI\"",
    "\"PIA\"",
    "\"QVA\"",
    "\"RFF\"",
    "\"SEL\"",
    "\"SGP\"",
    "\"TAX\"",
    "\"TCC\"",
    "\"TDT\"",
    "\"TMD\"",
    "\"TMP\"",
    "\"TOD\"",
    "\"TPL\"",
    "\"TSR\"",
    "\"UNA\"",
    "\"UNB\"",
    "\"UNE\"",
    "\"UNG\"",
    "\"UNH\"",
    "\"UNS\"",
    "\"UNT\"",
    "\"UNZ\"",
    "\"VLN\"",
    "<DATA>",
    "<NUMBER>",
    "\"\\\'\"",
    "\"+\"",
    "\":\"",
    "\"*\"",
  };

}
