/* Generated By:JavaCC: Do not edit this line. _911Constants.java */
package com.appliedmodels.edifact.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface _911Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AGR = 6;
  /** RegularExpression Id. */
  int AJT = 7;
  /** RegularExpression Id. */
  int ALC = 8;
  /** RegularExpression Id. */
  int ALI = 9;
  /** RegularExpression Id. */
  int API = 10;
  /** RegularExpression Id. */
  int AUT = 11;
  /** RegularExpression Id. */
  int BGM = 12;
  /** RegularExpression Id. */
  int BUS = 13;
  /** RegularExpression Id. */
  int CCI = 14;
  /** RegularExpression Id. */
  int CNI = 15;
  /** RegularExpression Id. */
  int CNT = 16;
  /** RegularExpression Id. */
  int COM = 17;
  /** RegularExpression Id. */
  int CPI = 18;
  /** RegularExpression Id. */
  int CPS = 19;
  /** RegularExpression Id. */
  int CST = 20;
  /** RegularExpression Id. */
  int CTA = 21;
  /** RegularExpression Id. */
  int CUX = 22;
  /** RegularExpression Id. */
  int DGS = 23;
  /** RegularExpression Id. */
  int DIM = 24;
  /** RegularExpression Id. */
  int DLI = 25;
  /** RegularExpression Id. */
  int DLM = 26;
  /** RegularExpression Id. */
  int DMS = 27;
  /** RegularExpression Id. */
  int DOC = 28;
  /** RegularExpression Id. */
  int DTM = 29;
  /** RegularExpression Id. */
  int EQA = 30;
  /** RegularExpression Id. */
  int EQD = 31;
  /** RegularExpression Id. */
  int EQN = 32;
  /** RegularExpression Id. */
  int ERC = 33;
  /** RegularExpression Id. */
  int ERP = 34;
  /** RegularExpression Id. */
  int FCA = 35;
  /** RegularExpression Id. */
  int FII = 36;
  /** RegularExpression Id. */
  int FTX = 37;
  /** RegularExpression Id. */
  int GDS = 38;
  /** RegularExpression Id. */
  int GID = 39;
  /** RegularExpression Id. */
  int GIN = 40;
  /** RegularExpression Id. */
  int GIR = 41;
  /** RegularExpression Id. */
  int GIS = 42;
  /** RegularExpression Id. */
  int GOR = 43;
  /** RegularExpression Id. */
  int HAN = 44;
  /** RegularExpression Id. */
  int IMD = 45;
  /** RegularExpression Id. */
  int INP = 46;
  /** RegularExpression Id. */
  int LIN = 47;
  /** RegularExpression Id. */
  int LOC = 48;
  /** RegularExpression Id. */
  int MEA = 49;
  /** RegularExpression Id. */
  int MOA = 50;
  /** RegularExpression Id. */
  int NAD = 51;
  /** RegularExpression Id. */
  int PAC = 52;
  /** RegularExpression Id. */
  int PAI = 53;
  /** RegularExpression Id. */
  int PAT = 54;
  /** RegularExpression Id. */
  int PCD = 55;
  /** RegularExpression Id. */
  int PCI = 56;
  /** RegularExpression Id. */
  int PGI = 57;
  /** RegularExpression Id. */
  int PIA = 58;
  /** RegularExpression Id. */
  int PIT = 59;
  /** RegularExpression Id. */
  int PRC = 60;
  /** RegularExpression Id. */
  int PRI = 61;
  /** RegularExpression Id. */
  int PSD = 62;
  /** RegularExpression Id. */
  int QTY = 63;
  /** RegularExpression Id. */
  int QVA = 64;
  /** RegularExpression Id. */
  int RCS = 65;
  /** RegularExpression Id. */
  int RFF = 66;
  /** RegularExpression Id. */
  int RNG = 67;
  /** RegularExpression Id. */
  int RTE = 68;
  /** RegularExpression Id. */
  int SCC = 69;
  /** RegularExpression Id. */
  int SEL = 70;
  /** RegularExpression Id. */
  int SEQ = 71;
  /** RegularExpression Id. */
  int SGP = 72;
  /** RegularExpression Id. */
  int SPS = 73;
  /** RegularExpression Id. */
  int STA = 74;
  /** RegularExpression Id. */
  int TAX = 75;
  /** RegularExpression Id. */
  int TCC = 76;
  /** RegularExpression Id. */
  int TDT = 77;
  /** RegularExpression Id. */
  int TEM = 78;
  /** RegularExpression Id. */
  int TMD = 79;
  /** RegularExpression Id. */
  int TMP = 80;
  /** RegularExpression Id. */
  int TOD = 81;
  /** RegularExpression Id. */
  int TPL = 82;
  /** RegularExpression Id. */
  int TSR = 83;
  /** RegularExpression Id. */
  int UCD = 84;
  /** RegularExpression Id. */
  int UCF = 85;
  /** RegularExpression Id. */
  int UCI = 86;
  /** RegularExpression Id. */
  int UCM = 87;
  /** RegularExpression Id. */
  int UCS = 88;
  /** RegularExpression Id. */
  int UGH = 89;
  /** RegularExpression Id. */
  int UGT = 90;
  /** RegularExpression Id. */
  int UIB = 91;
  /** RegularExpression Id. */
  int UIH = 92;
  /** RegularExpression Id. */
  int UIR = 93;
  /** RegularExpression Id. */
  int UIT = 94;
  /** RegularExpression Id. */
  int UIZ = 95;
  /** RegularExpression Id. */
  int UNB = 96;
  /** RegularExpression Id. */
  int UNE = 97;
  /** RegularExpression Id. */
  int UNG = 98;
  /** RegularExpression Id. */
  int UNH = 99;
  /** RegularExpression Id. */
  int UNO = 100;
  /** RegularExpression Id. */
  int UNP = 101;
  /** RegularExpression Id. */
  int UNS = 102;
  /** RegularExpression Id. */
  int UNT = 103;
  /** RegularExpression Id. */
  int UNZ = 104;
  /** RegularExpression Id. */
  int USA = 105;
  /** RegularExpression Id. */
  int USB = 106;
  /** RegularExpression Id. */
  int USC = 107;
  /** RegularExpression Id. */
  int USD = 108;
  /** RegularExpression Id. */
  int USE = 109;
  /** RegularExpression Id. */
  int USF = 110;
  /** RegularExpression Id. */
  int USH = 111;
  /** RegularExpression Id. */
  int USL = 112;
  /** RegularExpression Id. */
  int USR = 113;
  /** RegularExpression Id. */
  int UST = 114;
  /** RegularExpression Id. */
  int USU = 115;
  /** RegularExpression Id. */
  int USX = 116;
  /** RegularExpression Id. */
  int USY = 117;
  /** RegularExpression Id. */
  int DATA = 118;
  /** RegularExpression Id. */
  int NUMBER = 119;
  /** RegularExpression Id. */
  int SEGTERM = 120;
  /** RegularExpression Id. */
  int DATASEP = 121;
  /** RegularExpression Id. */
  int COMPDATASEP = 122;
  /** RegularExpression Id. */
  int REPEATSEP = 123;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"AGR\"",
    "\"AJT\"",
    "\"ALC\"",
    "\"ALI\"",
    "\"API\"",
    "\"AUT\"",
    "\"BGM\"",
    "\"BUS\"",
    "\"CCI\"",
    "\"CNI\"",
    "\"CNT\"",
    "\"COM\"",
    "\"CPI\"",
    "\"CPS\"",
    "\"CST\"",
    "\"CTA\"",
    "\"CUX\"",
    "\"DGS\"",
    "\"DIM\"",
    "\"DLI\"",
    "\"DLM\"",
    "\"DMS\"",
    "\"DOC\"",
    "\"DTM\"",
    "\"EQA\"",
    "\"EQD\"",
    "\"EQN\"",
    "\"ERC\"",
    "\"ERP\"",
    "\"FCA\"",
    "\"FII\"",
    "\"FTX\"",
    "\"GDS\"",
    "\"GID\"",
    "\"GIN\"",
    "\"GIR\"",
    "\"GIS\"",
    "\"GOR\"",
    "\"HAN\"",
    "\"IMD\"",
    "\"INP\"",
    "\"LIN\"",
    "\"LOC\"",
    "\"MEA\"",
    "\"MOA\"",
    "\"NAD\"",
    "\"PAC\"",
    "\"PAI\"",
    "\"PAT\"",
    "\"PCD\"",
    "\"PCI\"",
    "\"PGI\"",
    "\"PIA\"",
    "\"PIT\"",
    "\"PRC\"",
    "\"PRI\"",
    "\"PSD\"",
    "\"QTY\"",
    "\"QVA\"",
    "\"RCS\"",
    "\"RFF\"",
    "\"RNG\"",
    "\"RTE\"",
    "\"SCC\"",
    "\"SEL\"",
    "\"SEQ\"",
    "\"SGP\"",
    "\"SPS\"",
    "\"STA\"",
    "\"TAX\"",
    "\"TCC\"",
    "\"TDT\"",
    "\"TEM\"",
    "\"TMD\"",
    "\"TMP\"",
    "\"TOD\"",
    "\"TPL\"",
    "\"TSR\"",
    "\"UCD\"",
    "\"UCF\"",
    "\"UCI\"",
    "\"UCM\"",
    "\"UCS\"",
    "\"UGH\"",
    "\"UGT\"",
    "\"UIB\"",
    "\"UIH\"",
    "\"UIR\"",
    "\"UIT\"",
    "\"UIZ\"",
    "\"UNB\"",
    "\"UNE\"",
    "\"UNG\"",
    "\"UNH\"",
    "\"UNO\"",
    "\"UNP\"",
    "\"UNS\"",
    "\"UNT\"",
    "\"UNZ\"",
    "\"USA\"",
    "\"USB\"",
    "\"USC\"",
    "\"USD\"",
    "\"USE\"",
    "\"USF\"",
    "\"USH\"",
    "\"USL\"",
    "\"USR\"",
    "\"UST\"",
    "\"USU\"",
    "\"USX\"",
    "\"USY\"",
    "<DATA>",
    "<NUMBER>",
    "\"\\\'\"",
    "\"+\"",
    "\":\"",
    "\"*\"",
  };

}
