/* Generated By:JavaCC: Do not edit this line. _912Constants.java */
package com.appliedmodels.edifact.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface _912Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AJT = 6;
  /** RegularExpression Id. */
  int ALC = 7;
  /** RegularExpression Id. */
  int ALI = 8;
  /** RegularExpression Id. */
  int API = 9;
  /** RegularExpression Id. */
  int AUT = 10;
  /** RegularExpression Id. */
  int BGM = 11;
  /** RegularExpression Id. */
  int BUS = 12;
  /** RegularExpression Id. */
  int CHD = 13;
  /** RegularExpression Id. */
  int CNT = 14;
  /** RegularExpression Id. */
  int COM = 15;
  /** RegularExpression Id. */
  int CPI = 16;
  /** RegularExpression Id. */
  int CST = 17;
  /** RegularExpression Id. */
  int CTA = 18;
  /** RegularExpression Id. */
  int CUX = 19;
  /** RegularExpression Id. */
  int DCR = 20;
  /** RegularExpression Id. */
  int DGS = 21;
  /** RegularExpression Id. */
  int DIM = 22;
  /** RegularExpression Id. */
  int DLI = 23;
  /** RegularExpression Id. */
  int DMS = 24;
  /** RegularExpression Id. */
  int DOC = 25;
  /** RegularExpression Id. */
  int DTM = 26;
  /** RegularExpression Id. */
  int EQA = 27;
  /** RegularExpression Id. */
  int EQD = 28;
  /** RegularExpression Id. */
  int EQN = 29;
  /** RegularExpression Id. */
  int ERC = 30;
  /** RegularExpression Id. */
  int ERP = 31;
  /** RegularExpression Id. */
  int FCA = 32;
  /** RegularExpression Id. */
  int FII = 33;
  /** RegularExpression Id. */
  int FTX = 34;
  /** RegularExpression Id. */
  int GDS = 35;
  /** RegularExpression Id. */
  int GID = 36;
  /** RegularExpression Id. */
  int GIN = 37;
  /** RegularExpression Id. */
  int GIR = 38;
  /** RegularExpression Id. */
  int GIS = 39;
  /** RegularExpression Id. */
  int GOR = 40;
  /** RegularExpression Id. */
  int HAN = 41;
  /** RegularExpression Id. */
  int HIN = 42;
  /** RegularExpression Id. */
  int IMD = 43;
  /** RegularExpression Id. */
  int INP = 44;
  /** RegularExpression Id. */
  int LIN = 45;
  /** RegularExpression Id. */
  int LOC = 46;
  /** RegularExpression Id. */
  int LTM = 47;
  /** RegularExpression Id. */
  int MEA = 48;
  /** RegularExpression Id. */
  int MOA = 49;
  /** RegularExpression Id. */
  int NAD = 50;
  /** RegularExpression Id. */
  int PAC = 51;
  /** RegularExpression Id. */
  int PAI = 52;
  /** RegularExpression Id. */
  int PAT = 53;
  /** RegularExpression Id. */
  int PCI = 54;
  /** RegularExpression Id. */
  int PIA = 55;
  /** RegularExpression Id. */
  int QTY = 56;
  /** RegularExpression Id. */
  int QVA = 57;
  /** RegularExpression Id. */
  int RFF = 58;
  /** RegularExpression Id. */
  int SCC = 59;
  /** RegularExpression Id. */
  int SDQ = 60;
  /** RegularExpression Id. */
  int SEL = 61;
  /** RegularExpression Id. */
  int SGP = 62;
  /** RegularExpression Id. */
  int TAX = 63;
  /** RegularExpression Id. */
  int TCC = 64;
  /** RegularExpression Id. */
  int TDT = 65;
  /** RegularExpression Id. */
  int TMD = 66;
  /** RegularExpression Id. */
  int TMP = 67;
  /** RegularExpression Id. */
  int TOD = 68;
  /** RegularExpression Id. */
  int TPL = 69;
  /** RegularExpression Id. */
  int TSR = 70;
  /** RegularExpression Id. */
  int UNB = 71;
  /** RegularExpression Id. */
  int UNE = 72;
  /** RegularExpression Id. */
  int UNG = 73;
  /** RegularExpression Id. */
  int UNH = 74;
  /** RegularExpression Id. */
  int UNS = 75;
  /** RegularExpression Id. */
  int UNT = 76;
  /** RegularExpression Id. */
  int UNZ = 77;
  /** RegularExpression Id. */
  int VLN = 78;
  /** RegularExpression Id. */
  int DATA = 79;
  /** RegularExpression Id. */
  int NUMBER = 80;
  /** RegularExpression Id. */
  int SEGTERM = 81;
  /** RegularExpression Id. */
  int DATASEP = 82;
  /** RegularExpression Id. */
  int COMPDATASEP = 83;
  /** RegularExpression Id. */
  int REPEATSEP = 84;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"AJT\"",
    "\"ALC\"",
    "\"ALI\"",
    "\"API\"",
    "\"AUT\"",
    "\"BGM\"",
    "\"BUS\"",
    "\"CHD\"",
    "\"CNT\"",
    "\"COM\"",
    "\"CPI\"",
    "\"CST\"",
    "\"CTA\"",
    "\"CUX\"",
    "\"DCR\"",
    "\"DGS\"",
    "\"DIM\"",
    "\"DLI\"",
    "\"DMS\"",
    "\"DOC\"",
    "\"DTM\"",
    "\"EQA\"",
    "\"EQD\"",
    "\"EQN\"",
    "\"ERC\"",
    "\"ERP\"",
    "\"FCA\"",
    "\"FII\"",
    "\"FTX\"",
    "\"GDS\"",
    "\"GID\"",
    "\"GIN\"",
    "\"GIR\"",
    "\"GIS\"",
    "\"GOR\"",
    "\"HAN\"",
    "\"HIN\"",
    "\"IMD\"",
    "\"INP\"",
    "\"LIN\"",
    "\"LOC\"",
    "\"LTM\"",
    "\"MEA\"",
    "\"MOA\"",
    "\"NAD\"",
    "\"PAC\"",
    "\"PAI\"",
    "\"PAT\"",
    "\"PCI\"",
    "\"PIA\"",
    "\"QTY\"",
    "\"QVA\"",
    "\"RFF\"",
    "\"SCC\"",
    "\"SDQ\"",
    "\"SEL\"",
    "\"SGP\"",
    "\"TAX\"",
    "\"TCC\"",
    "\"TDT\"",
    "\"TMD\"",
    "\"TMP\"",
    "\"TOD\"",
    "\"TPL\"",
    "\"TSR\"",
    "\"UNB\"",
    "\"UNE\"",
    "\"UNG\"",
    "\"UNH\"",
    "\"UNS\"",
    "\"UNT\"",
    "\"UNZ\"",
    "\"VLN\"",
    "<DATA>",
    "<NUMBER>",
    "\"\\\'\"",
    "\"+\"",
    "\":\"",
    "\"*\"",
  };

}
