/* Generated By:JavaCC: Do not edit this line. _932Constants.java */
package com.appliedmodels.edifact.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface _932Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AJT = 6;
  /** RegularExpression Id. */
  int ALC = 7;
  /** RegularExpression Id. */
  int ALI = 8;
  /** RegularExpression Id. */
  int API = 9;
  /** RegularExpression Id. */
  int AUT = 10;
  /** RegularExpression Id. */
  int BGM = 11;
  /** RegularExpression Id. */
  int BUS = 12;
  /** RegularExpression Id. */
  int CCI = 13;
  /** RegularExpression Id. */
  int CNI = 14;
  /** RegularExpression Id. */
  int CNT = 15;
  /** RegularExpression Id. */
  int COM = 16;
  /** RegularExpression Id. */
  int CPI = 17;
  /** RegularExpression Id. */
  int CST = 18;
  /** RegularExpression Id. */
  int CTA = 19;
  /** RegularExpression Id. */
  int CUX = 20;
  /** RegularExpression Id. */
  int DGS = 21;
  /** RegularExpression Id. */
  int DIM = 22;
  /** RegularExpression Id. */
  int DLI = 23;
  /** RegularExpression Id. */
  int DLM = 24;
  /** RegularExpression Id. */
  int DMS = 25;
  /** RegularExpression Id. */
  int DOC = 26;
  /** RegularExpression Id. */
  int DTM = 27;
  /** RegularExpression Id. */
  int EQA = 28;
  /** RegularExpression Id. */
  int EQD = 29;
  /** RegularExpression Id. */
  int EQN = 30;
  /** RegularExpression Id. */
  int ERC = 31;
  /** RegularExpression Id. */
  int ERP = 32;
  /** RegularExpression Id. */
  int FCA = 33;
  /** RegularExpression Id. */
  int FII = 34;
  /** RegularExpression Id. */
  int FTX = 35;
  /** RegularExpression Id. */
  int GDS = 36;
  /** RegularExpression Id. */
  int GID = 37;
  /** RegularExpression Id. */
  int GIN = 38;
  /** RegularExpression Id. */
  int GIR = 39;
  /** RegularExpression Id. */
  int GIS = 40;
  /** RegularExpression Id. */
  int GOR = 41;
  /** RegularExpression Id. */
  int HAN = 42;
  /** RegularExpression Id. */
  int IMD = 43;
  /** RegularExpression Id. */
  int INP = 44;
  /** RegularExpression Id. */
  int LIN = 45;
  /** RegularExpression Id. */
  int LOC = 46;
  /** RegularExpression Id. */
  int MEA = 47;
  /** RegularExpression Id. */
  int MOA = 48;
  /** RegularExpression Id. */
  int NAD = 49;
  /** RegularExpression Id. */
  int PAC = 50;
  /** RegularExpression Id. */
  int PAI = 51;
  /** RegularExpression Id. */
  int PAT = 52;
  /** RegularExpression Id. */
  int PCD = 53;
  /** RegularExpression Id. */
  int PCI = 54;
  /** RegularExpression Id. */
  int PGI = 55;
  /** RegularExpression Id. */
  int PIA = 56;
  /** RegularExpression Id. */
  int PRC = 57;
  /** RegularExpression Id. */
  int PRI = 58;
  /** RegularExpression Id. */
  int PSD = 59;
  /** RegularExpression Id. */
  int QTY = 60;
  /** RegularExpression Id. */
  int QVA = 61;
  /** RegularExpression Id. */
  int RCS = 62;
  /** RegularExpression Id. */
  int RFF = 63;
  /** RegularExpression Id. */
  int RNG = 64;
  /** RegularExpression Id. */
  int RTE = 65;
  /** RegularExpression Id. */
  int SCC = 66;
  /** RegularExpression Id. */
  int SEL = 67;
  /** RegularExpression Id. */
  int SEQ = 68;
  /** RegularExpression Id. */
  int SGP = 69;
  /** RegularExpression Id. */
  int SPS = 70;
  /** RegularExpression Id. */
  int STA = 71;
  /** RegularExpression Id. */
  int TAX = 72;
  /** RegularExpression Id. */
  int TCC = 73;
  /** RegularExpression Id. */
  int TDT = 74;
  /** RegularExpression Id. */
  int TEM = 75;
  /** RegularExpression Id. */
  int TMD = 76;
  /** RegularExpression Id. */
  int TMP = 77;
  /** RegularExpression Id. */
  int TOD = 78;
  /** RegularExpression Id. */
  int TPL = 79;
  /** RegularExpression Id. */
  int TSR = 80;
  /** RegularExpression Id. */
  int UCD = 81;
  /** RegularExpression Id. */
  int UCF = 82;
  /** RegularExpression Id. */
  int UCI = 83;
  /** RegularExpression Id. */
  int UCM = 84;
  /** RegularExpression Id. */
  int UCS = 85;
  /** RegularExpression Id. */
  int UGH = 86;
  /** RegularExpression Id. */
  int UGT = 87;
  /** RegularExpression Id. */
  int UIB = 88;
  /** RegularExpression Id. */
  int UIH = 89;
  /** RegularExpression Id. */
  int UIR = 90;
  /** RegularExpression Id. */
  int UIT = 91;
  /** RegularExpression Id. */
  int UIZ = 92;
  /** RegularExpression Id. */
  int UNB = 93;
  /** RegularExpression Id. */
  int UNE = 94;
  /** RegularExpression Id. */
  int UNG = 95;
  /** RegularExpression Id. */
  int UNH = 96;
  /** RegularExpression Id. */
  int UNO = 97;
  /** RegularExpression Id. */
  int UNP = 98;
  /** RegularExpression Id. */
  int UNS = 99;
  /** RegularExpression Id. */
  int UNT = 100;
  /** RegularExpression Id. */
  int UNZ = 101;
  /** RegularExpression Id. */
  int USA = 102;
  /** RegularExpression Id. */
  int USB = 103;
  /** RegularExpression Id. */
  int USC = 104;
  /** RegularExpression Id. */
  int USD = 105;
  /** RegularExpression Id. */
  int USE = 106;
  /** RegularExpression Id. */
  int USF = 107;
  /** RegularExpression Id. */
  int USH = 108;
  /** RegularExpression Id. */
  int USL = 109;
  /** RegularExpression Id. */
  int USR = 110;
  /** RegularExpression Id. */
  int UST = 111;
  /** RegularExpression Id. */
  int USU = 112;
  /** RegularExpression Id. */
  int USX = 113;
  /** RegularExpression Id. */
  int USY = 114;
  /** RegularExpression Id. */
  int DATA = 115;
  /** RegularExpression Id. */
  int NUMBER = 116;
  /** RegularExpression Id. */
  int SEGTERM = 117;
  /** RegularExpression Id. */
  int DATASEP = 118;
  /** RegularExpression Id. */
  int COMPDATASEP = 119;
  /** RegularExpression Id. */
  int REPEATSEP = 120;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"AJT\"",
    "\"ALC\"",
    "\"ALI\"",
    "\"API\"",
    "\"AUT\"",
    "\"BGM\"",
    "\"BUS\"",
    "\"CCI\"",
    "\"CNI\"",
    "\"CNT\"",
    "\"COM\"",
    "\"CPI\"",
    "\"CST\"",
    "\"CTA\"",
    "\"CUX\"",
    "\"DGS\"",
    "\"DIM\"",
    "\"DLI\"",
    "\"DLM\"",
    "\"DMS\"",
    "\"DOC\"",
    "\"DTM\"",
    "\"EQA\"",
    "\"EQD\"",
    "\"EQN\"",
    "\"ERC\"",
    "\"ERP\"",
    "\"FCA\"",
    "\"FII\"",
    "\"FTX\"",
    "\"GDS\"",
    "\"GID\"",
    "\"GIN\"",
    "\"GIR\"",
    "\"GIS\"",
    "\"GOR\"",
    "\"HAN\"",
    "\"IMD\"",
    "\"INP\"",
    "\"LIN\"",
    "\"LOC\"",
    "\"MEA\"",
    "\"MOA\"",
    "\"NAD\"",
    "\"PAC\"",
    "\"PAI\"",
    "\"PAT\"",
    "\"PCD\"",
    "\"PCI\"",
    "\"PGI\"",
    "\"PIA\"",
    "\"PRC\"",
    "\"PRI\"",
    "\"PSD\"",
    "\"QTY\"",
    "\"QVA\"",
    "\"RCS\"",
    "\"RFF\"",
    "\"RNG\"",
    "\"RTE\"",
    "\"SCC\"",
    "\"SEL\"",
    "\"SEQ\"",
    "\"SGP\"",
    "\"SPS\"",
    "\"STA\"",
    "\"TAX\"",
    "\"TCC\"",
    "\"TDT\"",
    "\"TEM\"",
    "\"TMD\"",
    "\"TMP\"",
    "\"TOD\"",
    "\"TPL\"",
    "\"TSR\"",
    "\"UCD\"",
    "\"UCF\"",
    "\"UCI\"",
    "\"UCM\"",
    "\"UCS\"",
    "\"UGH\"",
    "\"UGT\"",
    "\"UIB\"",
    "\"UIH\"",
    "\"UIR\"",
    "\"UIT\"",
    "\"UIZ\"",
    "\"UNB\"",
    "\"UNE\"",
    "\"UNG\"",
    "\"UNH\"",
    "\"UNO\"",
    "\"UNP\"",
    "\"UNS\"",
    "\"UNT\"",
    "\"UNZ\"",
    "\"USA\"",
    "\"USB\"",
    "\"USC\"",
    "\"USD\"",
    "\"USE\"",
    "\"USF\"",
    "\"USH\"",
    "\"USL\"",
    "\"USR\"",
    "\"UST\"",
    "\"USU\"",
    "\"USX\"",
    "\"USY\"",
    "<DATA>",
    "<NUMBER>",
    "\"\\\'\"",
    "\"+\"",
    "\":\"",
    "\"*\"",
  };

}
