/* Generated By:JavaCC: Do not edit this line. D11AConstants.java */
package com.appliedmodels.edifact.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface D11AConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADR = 6;
  /** RegularExpression Id. */
  int AGR = 7;
  /** RegularExpression Id. */
  int AJT = 8;
  /** RegularExpression Id. */
  int ALC = 9;
  /** RegularExpression Id. */
  int ALI = 10;
  /** RegularExpression Id. */
  int APP = 11;
  /** RegularExpression Id. */
  int APR = 12;
  /** RegularExpression Id. */
  int ARD = 13;
  /** RegularExpression Id. */
  int ARR = 14;
  /** RegularExpression Id. */
  int ASI = 15;
  /** RegularExpression Id. */
  int ATT = 16;
  /** RegularExpression Id. */
  int AUT = 17;
  /** RegularExpression Id. */
  int BAS = 18;
  /** RegularExpression Id. */
  int BGM = 19;
  /** RegularExpression Id. */
  int BII = 20;
  /** RegularExpression Id. */
  int BUS = 21;
  /** RegularExpression Id. */
  int CAV = 22;
  /** RegularExpression Id. */
  int CCD = 23;
  /** RegularExpression Id. */
  int CCI = 24;
  /** RegularExpression Id. */
  int CDI = 25;
  /** RegularExpression Id. */
  int CDS = 26;
  /** RegularExpression Id. */
  int CDV = 27;
  /** RegularExpression Id. */
  int CED = 28;
  /** RegularExpression Id. */
  int CIN = 29;
  /** RegularExpression Id. */
  int CLA = 30;
  /** RegularExpression Id. */
  int CLI = 31;
  /** RegularExpression Id. */
  int CMP = 32;
  /** RegularExpression Id. */
  int CNI = 33;
  /** RegularExpression Id. */
  int CNT = 34;
  /** RegularExpression Id. */
  int COD = 35;
  /** RegularExpression Id. */
  int COM = 36;
  /** RegularExpression Id. */
  int COT = 37;
  /** RegularExpression Id. */
  int CPI = 38;
  /** RegularExpression Id. */
  int CPS = 39;
  /** RegularExpression Id. */
  int CPT = 40;
  /** RegularExpression Id. */
  int CST = 41;
  /** RegularExpression Id. */
  int CTA = 42;
  /** RegularExpression Id. */
  int CUX = 43;
  /** RegularExpression Id. */
  int DAM = 44;
  /** RegularExpression Id. */
  int DFN = 45;
  /** RegularExpression Id. */
  int DGS = 46;
  /** RegularExpression Id. */
  int DII = 47;
  /** RegularExpression Id. */
  int DIM = 48;
  /** RegularExpression Id. */
  int DLI = 49;
  /** RegularExpression Id. */
  int DLM = 50;
  /** RegularExpression Id. */
  int DMS = 51;
  /** RegularExpression Id. */
  int DOC = 52;
  /** RegularExpression Id. */
  int DRD = 53;
  /** RegularExpression Id. */
  int DSG = 54;
  /** RegularExpression Id. */
  int DSI = 55;
  /** RegularExpression Id. */
  int DTM = 56;
  /** RegularExpression Id. */
  int EDT = 57;
  /** RegularExpression Id. */
  int EFI = 58;
  /** RegularExpression Id. */
  int ELM = 59;
  /** RegularExpression Id. */
  int ELU = 60;
  /** RegularExpression Id. */
  int ELV = 61;
  /** RegularExpression Id. */
  int EMP = 62;
  /** RegularExpression Id. */
  int EQA = 63;
  /** RegularExpression Id. */
  int EQD = 64;
  /** RegularExpression Id. */
  int EQN = 65;
  /** RegularExpression Id. */
  int ERC = 66;
  /** RegularExpression Id. */
  int ERP = 67;
  /** RegularExpression Id. */
  int EVE = 68;
  /** RegularExpression Id. */
  int FCA = 69;
  /** RegularExpression Id. */
  int FII = 70;
  /** RegularExpression Id. */
  int FNS = 71;
  /** RegularExpression Id. */
  int FNT = 72;
  /** RegularExpression Id. */
  int FOR = 73;
  /** RegularExpression Id. */
  int FSQ = 74;
  /** RegularExpression Id. */
  int FTX = 75;
  /** RegularExpression Id. */
  int GDS = 76;
  /** RegularExpression Id. */
  int GEI = 77;
  /** RegularExpression Id. */
  int GID = 78;
  /** RegularExpression Id. */
  int GIN = 79;
  /** RegularExpression Id. */
  int GIR = 80;
  /** RegularExpression Id. */
  int GOR = 81;
  /** RegularExpression Id. */
  int GPO = 82;
  /** RegularExpression Id. */
  int GRU = 83;
  /** RegularExpression Id. */
  int HAN = 84;
  /** RegularExpression Id. */
  int HYN = 85;
  /** RegularExpression Id. */
  int ICD = 86;
  /** RegularExpression Id. */
  int IDE = 87;
  /** RegularExpression Id. */
  int IFD = 88;
  /** RegularExpression Id. */
  int IHC = 89;
  /** RegularExpression Id. */
  int IMD = 90;
  /** RegularExpression Id. */
  int IND = 91;
  /** RegularExpression Id. */
  int INP = 92;
  /** RegularExpression Id. */
  int INV = 93;
  /** RegularExpression Id. */
  int IRQ = 94;
  /** RegularExpression Id. */
  int LAN = 95;
  /** RegularExpression Id. */
  int LIN = 96;
  /** RegularExpression Id. */
  int LOC = 97;
  /** RegularExpression Id. */
  int MEA = 98;
  /** RegularExpression Id. */
  int MEM = 99;
  /** RegularExpression Id. */
  int MKS = 100;
  /** RegularExpression Id. */
  int MOA = 101;
  /** RegularExpression Id. */
  int MSG = 102;
  /** RegularExpression Id. */
  int MTD = 103;
  /** RegularExpression Id. */
  int NAD = 104;
  /** RegularExpression Id. */
  int NAT = 105;
  /** RegularExpression Id. */
  int PAC = 106;
  /** RegularExpression Id. */
  int PAI = 107;
  /** RegularExpression Id. */
  int PAS = 108;
  /** RegularExpression Id. */
  int PCC = 109;
  /** RegularExpression Id. */
  int PCD = 110;
  /** RegularExpression Id. */
  int PCI = 111;
  /** RegularExpression Id. */
  int PDI = 112;
  /** RegularExpression Id. */
  int PER = 113;
  /** RegularExpression Id. */
  int PGI = 114;
  /** RegularExpression Id. */
  int PIA = 115;
  /** RegularExpression Id. */
  int PNA = 116;
  /** RegularExpression Id. */
  int POC = 117;
  /** RegularExpression Id. */
  int PRC = 118;
  /** RegularExpression Id. */
  int PRI = 119;
  /** RegularExpression Id. */
  int PRV = 120;
  /** RegularExpression Id. */
  int PSD = 121;
  /** RegularExpression Id. */
  int PTY = 122;
  /** RegularExpression Id. */
  int PYT = 123;
  /** RegularExpression Id. */
  int QRS = 124;
  /** RegularExpression Id. */
  int QTY = 125;
  /** RegularExpression Id. */
  int QUA = 126;
  /** RegularExpression Id. */
  int QVR = 127;
  /** RegularExpression Id. */
  int RCS = 128;
  /** RegularExpression Id. */
  int REL = 129;
  /** RegularExpression Id. */
  int RFF = 130;
  /** RegularExpression Id. */
  int RJL = 131;
  /** RegularExpression Id. */
  int RNG = 132;
  /** RegularExpression Id. */
  int ROD = 133;
  /** RegularExpression Id. */
  int RSL = 134;
  /** RegularExpression Id. */
  int RTE = 135;
  /** RegularExpression Id. */
  int SAL = 136;
  /** RegularExpression Id. */
  int SCC = 137;
  /** RegularExpression Id. */
  int SCD = 138;
  /** RegularExpression Id. */
  int SEG = 139;
  /** RegularExpression Id. */
  int SEL = 140;
  /** RegularExpression Id. */
  int SEQ = 141;
  /** RegularExpression Id. */
  int SFI = 142;
  /** RegularExpression Id. */
  int SGP = 143;
  /** RegularExpression Id. */
  int SGU = 144;
  /** RegularExpression Id. */
  int SPR = 145;
  /** RegularExpression Id. */
  int SPS = 146;
  /** RegularExpression Id. */
  int STA = 147;
  /** RegularExpression Id. */
  int STC = 148;
  /** RegularExpression Id. */
  int STG = 149;
  /** RegularExpression Id. */
  int STS = 150;
  /** RegularExpression Id. */
  int TAX = 151;
  /** RegularExpression Id. */
  int TCC = 152;
  /** RegularExpression Id. */
  int TDT = 153;
  /** RegularExpression Id. */
  int TEM = 154;
  /** RegularExpression Id. */
  int TMD = 155;
  /** RegularExpression Id. */
  int TMP = 156;
  /** RegularExpression Id. */
  int TOD = 157;
  /** RegularExpression Id. */
  int TPL = 158;
  /** RegularExpression Id. */
  int TRU = 159;
  /** RegularExpression Id. */
  int TSR = 160;
  /** RegularExpression Id. */
  int VLI = 161;
  /** RegularExpression Id. */
  int UCD = 162;
  /** RegularExpression Id. */
  int UCF = 163;
  /** RegularExpression Id. */
  int UCI = 164;
  /** RegularExpression Id. */
  int UCM = 165;
  /** RegularExpression Id. */
  int UCS = 166;
  /** RegularExpression Id. */
  int UGH = 167;
  /** RegularExpression Id. */
  int UGT = 168;
  /** RegularExpression Id. */
  int UIB = 169;
  /** RegularExpression Id. */
  int UIH = 170;
  /** RegularExpression Id. */
  int UIR = 171;
  /** RegularExpression Id. */
  int UIT = 172;
  /** RegularExpression Id. */
  int UIZ = 173;
  /** RegularExpression Id. */
  int UNB = 174;
  /** RegularExpression Id. */
  int UNE = 175;
  /** RegularExpression Id. */
  int UNG = 176;
  /** RegularExpression Id. */
  int UNH = 177;
  /** RegularExpression Id. */
  int UNO = 178;
  /** RegularExpression Id. */
  int UNP = 179;
  /** RegularExpression Id. */
  int UNS = 180;
  /** RegularExpression Id. */
  int UNT = 181;
  /** RegularExpression Id. */
  int UNZ = 182;
  /** RegularExpression Id. */
  int USA = 183;
  /** RegularExpression Id. */
  int USB = 184;
  /** RegularExpression Id. */
  int USC = 185;
  /** RegularExpression Id. */
  int USD = 186;
  /** RegularExpression Id. */
  int USE = 187;
  /** RegularExpression Id. */
  int USF = 188;
  /** RegularExpression Id. */
  int USH = 189;
  /** RegularExpression Id. */
  int USL = 190;
  /** RegularExpression Id. */
  int USR = 191;
  /** RegularExpression Id. */
  int UST = 192;
  /** RegularExpression Id. */
  int USU = 193;
  /** RegularExpression Id. */
  int USX = 194;
  /** RegularExpression Id. */
  int USY = 195;
  /** RegularExpression Id. */
  int AAI = 196;
  /** RegularExpression Id. */
  int ADI = 197;
  /** RegularExpression Id. */
  int ADS = 198;
  /** RegularExpression Id. */
  int ALS = 199;
  /** RegularExpression Id. */
  int APD = 200;
  /** RegularExpression Id. */
  int ASD = 201;
  /** RegularExpression Id. */
  int ATI = 202;
  /** RegularExpression Id. */
  int ATR = 203;
  /** RegularExpression Id. */
  int BCD = 204;
  /** RegularExpression Id. */
  int BLI = 205;
  /** RegularExpression Id. */
  int CLT = 206;
  /** RegularExpression Id. */
  int CMN = 207;
  /** RegularExpression Id. */
  int CNX = 208;
  /** RegularExpression Id. */
  int CNY = 209;
  /** RegularExpression Id. */
  int CON = 210;
  /** RegularExpression Id. */
  int CRI = 211;
  /** RegularExpression Id. */
  int CUR = 212;
  /** RegularExpression Id. */
  int DAV = 213;
  /** RegularExpression Id. */
  int DIS = 214;
  /** RegularExpression Id. */
  int DNT = 215;
  /** RegularExpression Id. */
  int DTI = 216;
  /** RegularExpression Id. */
  int ERI = 217;
  /** RegularExpression Id. */
  int FRM = 218;
  /** RegularExpression Id. */
  int FRQ = 219;
  /** RegularExpression Id. */
  int FTI = 220;
  /** RegularExpression Id. */
  int HDI = 221;
  /** RegularExpression Id. */
  int HDR = 222;
  /** RegularExpression Id. */
  int HDS = 223;
  /** RegularExpression Id. */
  int ICI = 224;
  /** RegularExpression Id. */
  int IFT = 225;
  /** RegularExpression Id. */
  int ITC = 226;
  /** RegularExpression Id. */
  int ITD = 227;
  /** RegularExpression Id. */
  int ITM = 228;
  /** RegularExpression Id. */
  int LKP = 229;
  /** RegularExpression Id. */
  int LNG = 230;
  /** RegularExpression Id. */
  int MAP = 231;
  /** RegularExpression Id. */
  int MES = 232;
  /** RegularExpression Id. */
  int MOV = 233;
  /** RegularExpression Id. */
  int MSD = 234;
  /** RegularExpression Id. */
  int NAA = 235;
  /** RegularExpression Id. */
  int NME = 236;
  /** RegularExpression Id. */
  int NUN = 237;
  /** RegularExpression Id. */
  int ODI = 238;
  /** RegularExpression Id. */
  int ODS = 239;
  /** RegularExpression Id. */
  int ORG = 240;
  /** RegularExpression Id. */
  int OTI = 241;
  /** RegularExpression Id. */
  int PDT = 242;
  /** RegularExpression Id. */
  int PLI = 243;
  /** RegularExpression Id. */
  int PMT = 244;
  /** RegularExpression Id. */
  int POP = 245;
  /** RegularExpression Id. */
  int POR = 246;
  /** RegularExpression Id. */
  int POS = 247;
  /** RegularExpression Id. */
  int PRD = 248;
  /** RegularExpression Id. */
  int PRE = 249;
  /** RegularExpression Id. */
  int PRO = 250;
  /** RegularExpression Id. */
  int PRT = 251;
  /** RegularExpression Id. */
  int PSI = 252;
  /** RegularExpression Id. */
  int QTI = 253;
  /** RegularExpression Id. */
  int RCI = 254;
  /** RegularExpression Id. */
  int RFR = 255;
  /** RegularExpression Id. */
  int RLS = 256;
  /** RegularExpression Id. */
  int RPI = 257;
  /** RegularExpression Id. */
  int RTC = 258;
  /** RegularExpression Id. */
  int RTI = 259;
  /** RegularExpression Id. */
  int RUL = 260;
  /** RegularExpression Id. */
  int SDT = 261;
  /** RegularExpression Id. */
  int SER = 262;
  /** RegularExpression Id. */
  int SSR = 263;
  /** RegularExpression Id. */
  int TCE = 264;
  /** RegularExpression Id. */
  int TDI = 265;
  /** RegularExpression Id. */
  int TFF = 266;
  /** RegularExpression Id. */
  int TIF = 267;
  /** RegularExpression Id. */
  int TIZ = 268;
  /** RegularExpression Id. */
  int TRF = 269;
  /** RegularExpression Id. */
  int TVL = 270;
  /** RegularExpression Id. */
  int TXS = 271;
  /** RegularExpression Id. */
  int VEH = 272;
  /** RegularExpression Id. */
  int DATA = 273;
  /** RegularExpression Id. */
  int NUMBER = 274;
  /** RegularExpression Id. */
  int SEGTERM = 275;
  /** RegularExpression Id. */
  int DATASEP = 276;
  /** RegularExpression Id. */
  int COMPDATASEP = 277;
  /** RegularExpression Id. */
  int REPEATSEP = 278;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"ADR\"",
    "\"AGR\"",
    "\"AJT\"",
    "\"ALC\"",
    "\"ALI\"",
    "\"APP\"",
    "\"APR\"",
    "\"ARD\"",
    "\"ARR\"",
    "\"ASI\"",
    "\"ATT\"",
    "\"AUT\"",
    "\"BAS\"",
    "\"BGM\"",
    "\"BII\"",
    "\"BUS\"",
    "\"CAV\"",
    "\"CCD\"",
    "\"CCI\"",
    "\"CDI\"",
    "\"CDS\"",
    "\"CDV\"",
    "\"CED\"",
    "\"CIN\"",
    "\"CLA\"",
    "\"CLI\"",
    "\"CMP\"",
    "\"CNI\"",
    "\"CNT\"",
    "\"COD\"",
    "\"COM\"",
    "\"COT\"",
    "\"CPI\"",
    "\"CPS\"",
    "\"CPT\"",
    "\"CST\"",
    "\"CTA\"",
    "\"CUX\"",
    "\"DAM\"",
    "\"DFN\"",
    "\"DGS\"",
    "\"DII\"",
    "\"DIM\"",
    "\"DLI\"",
    "\"DLM\"",
    "\"DMS\"",
    "\"DOC\"",
    "\"DRD\"",
    "\"DSG\"",
    "\"DSI\"",
    "\"DTM\"",
    "\"EDT\"",
    "\"EFI\"",
    "\"ELM\"",
    "\"ELU\"",
    "\"ELV\"",
    "\"EMP\"",
    "\"EQA\"",
    "\"EQD\"",
    "\"EQN\"",
    "\"ERC\"",
    "\"ERP\"",
    "\"EVE\"",
    "\"FCA\"",
    "\"FII\"",
    "\"FNS\"",
    "\"FNT\"",
    "\"FOR\"",
    "\"FSQ\"",
    "\"FTX\"",
    "\"GDS\"",
    "\"GEI\"",
    "\"GID\"",
    "\"GIN\"",
    "\"GIR\"",
    "\"GOR\"",
    "\"GPO\"",
    "\"GRU\"",
    "\"HAN\"",
    "\"HYN\"",
    "\"ICD\"",
    "\"IDE\"",
    "\"IFD\"",
    "\"IHC\"",
    "\"IMD\"",
    "\"IND\"",
    "\"INP\"",
    "\"INV\"",
    "\"IRQ\"",
    "\"LAN\"",
    "\"LIN\"",
    "\"LOC\"",
    "\"MEA\"",
    "\"MEM\"",
    "\"MKS\"",
    "\"MOA\"",
    "\"MSG\"",
    "\"MTD\"",
    "\"NAD\"",
    "\"NAT\"",
    "\"PAC\"",
    "\"PAI\"",
    "\"PAS\"",
    "\"PCC\"",
    "\"PCD\"",
    "\"PCI\"",
    "\"PDI\"",
    "\"PER\"",
    "\"PGI\"",
    "\"PIA\"",
    "\"PNA\"",
    "\"POC\"",
    "\"PRC\"",
    "\"PRI\"",
    "\"PRV\"",
    "\"PSD\"",
    "\"PTY\"",
    "\"PYT\"",
    "\"QRS\"",
    "\"QTY\"",
    "\"QUA\"",
    "\"QVR\"",
    "\"RCS\"",
    "\"REL\"",
    "\"RFF\"",
    "\"RJL\"",
    "\"RNG\"",
    "\"ROD\"",
    "\"RSL\"",
    "\"RTE\"",
    "\"SAL\"",
    "\"SCC\"",
    "\"SCD\"",
    "\"SEG\"",
    "\"SEL\"",
    "\"SEQ\"",
    "\"SFI\"",
    "\"SGP\"",
    "\"SGU\"",
    "\"SPR\"",
    "\"SPS\"",
    "\"STA\"",
    "\"STC\"",
    "\"STG\"",
    "\"STS\"",
    "\"TAX\"",
    "\"TCC\"",
    "\"TDT\"",
    "\"TEM\"",
    "\"TMD\"",
    "\"TMP\"",
    "\"TOD\"",
    "\"TPL\"",
    "\"TRU\"",
    "\"TSR\"",
    "\"VLI\"",
    "\"UCD\"",
    "\"UCF\"",
    "\"UCI\"",
    "\"UCM\"",
    "\"UCS\"",
    "\"UGH\"",
    "\"UGT\"",
    "\"UIB\"",
    "\"UIH\"",
    "\"UIR\"",
    "\"UIT\"",
    "\"UIZ\"",
    "\"UNB\"",
    "\"UNE\"",
    "\"UNG\"",
    "\"UNH\"",
    "\"UNO\"",
    "\"UNP\"",
    "\"UNS\"",
    "\"UNT\"",
    "\"UNZ\"",
    "\"USA\"",
    "\"USB\"",
    "\"USC\"",
    "\"USD\"",
    "\"USE\"",
    "\"USF\"",
    "\"USH\"",
    "\"USL\"",
    "\"USR\"",
    "\"UST\"",
    "\"USU\"",
    "\"USX\"",
    "\"USY\"",
    "\"AAI\"",
    "\"ADI\"",
    "\"ADS\"",
    "\"ALS\"",
    "\"APD\"",
    "\"ASD\"",
    "\"ATI\"",
    "\"ATR\"",
    "\"BCD\"",
    "\"BLI\"",
    "\"CLT\"",
    "\"CMN\"",
    "\"CNX\"",
    "\"CNY\"",
    "\"CON\"",
    "\"CRI\"",
    "\"CUR\"",
    "\"DAV\"",
    "\"DIS\"",
    "\"DNT\"",
    "\"DTI\"",
    "\"ERI\"",
    "\"FRM\"",
    "\"FRQ\"",
    "\"FTI\"",
    "\"HDI\"",
    "\"HDR\"",
    "\"HDS\"",
    "\"ICI\"",
    "\"IFT\"",
    "\"ITC\"",
    "\"ITD\"",
    "\"ITM\"",
    "\"LKP\"",
    "\"LNG\"",
    "\"MAP\"",
    "\"MES\"",
    "\"MOV\"",
    "\"MSD\"",
    "\"NAA\"",
    "\"NME\"",
    "\"NUN\"",
    "\"ODI\"",
    "\"ODS\"",
    "\"ORG\"",
    "\"OTI\"",
    "\"PDT\"",
    "\"PLI\"",
    "\"PMT\"",
    "\"POP\"",
    "\"POR\"",
    "\"POS\"",
    "\"PRD\"",
    "\"PRE\"",
    "\"PRO\"",
    "\"PRT\"",
    "\"PSI\"",
    "\"QTI\"",
    "\"RCI\"",
    "\"RFR\"",
    "\"RLS\"",
    "\"RPI\"",
    "\"RTC\"",
    "\"RTI\"",
    "\"RUL\"",
    "\"SDT\"",
    "\"SER\"",
    "\"SSR\"",
    "\"TCE\"",
    "\"TDI\"",
    "\"TFF\"",
    "\"TIF\"",
    "\"TIZ\"",
    "\"TRF\"",
    "\"TVL\"",
    "\"TXS\"",
    "\"VEH\"",
    "<DATA>",
    "<NUMBER>",
    "\"\\\'\"",
    "\"+\"",
    "\":\"",
    "\"*\"",
  };

}
