/* Generated By:JavaCC: Do not edit this line. D93AConstants.java */
package com.appliedmodels.edifact.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface D93AConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AGR = 6;
  /** RegularExpression Id. */
  int AJT = 7;
  /** RegularExpression Id. */
  int ALC = 8;
  /** RegularExpression Id. */
  int ALI = 9;
  /** RegularExpression Id. */
  int API = 10;
  /** RegularExpression Id. */
  int APR = 11;
  /** RegularExpression Id. */
  int ARD = 12;
  /** RegularExpression Id. */
  int ATT = 13;
  /** RegularExpression Id. */
  int AUT = 14;
  /** RegularExpression Id. */
  int BGM = 15;
  /** RegularExpression Id. */
  int BII = 16;
  /** RegularExpression Id. */
  int BUS = 17;
  /** RegularExpression Id. */
  int CCI = 18;
  /** RegularExpression Id. */
  int CNI = 19;
  /** RegularExpression Id. */
  int CNT = 20;
  /** RegularExpression Id. */
  int COM = 21;
  /** RegularExpression Id. */
  int COT = 22;
  /** RegularExpression Id. */
  int CPI = 23;
  /** RegularExpression Id. */
  int CPS = 24;
  /** RegularExpression Id. */
  int CST = 25;
  /** RegularExpression Id. */
  int CTA = 26;
  /** RegularExpression Id. */
  int CUX = 27;
  /** RegularExpression Id. */
  int DGS = 28;
  /** RegularExpression Id. */
  int DIM = 29;
  /** RegularExpression Id. */
  int DLI = 30;
  /** RegularExpression Id. */
  int DLM = 31;
  /** RegularExpression Id. */
  int DMS = 32;
  /** RegularExpression Id. */
  int DOC = 33;
  /** RegularExpression Id. */
  int DTM = 34;
  /** RegularExpression Id. */
  int EMP = 35;
  /** RegularExpression Id. */
  int EQA = 36;
  /** RegularExpression Id. */
  int EQD = 37;
  /** RegularExpression Id. */
  int EQN = 38;
  /** RegularExpression Id. */
  int ERC = 39;
  /** RegularExpression Id. */
  int ERP = 40;
  /** RegularExpression Id. */
  int FCA = 41;
  /** RegularExpression Id. */
  int FII = 42;
  /** RegularExpression Id. */
  int FTX = 43;
  /** RegularExpression Id. */
  int GDS = 44;
  /** RegularExpression Id. */
  int GID = 45;
  /** RegularExpression Id. */
  int GIN = 46;
  /** RegularExpression Id. */
  int GIR = 47;
  /** RegularExpression Id. */
  int GIS = 48;
  /** RegularExpression Id. */
  int GOR = 49;
  /** RegularExpression Id. */
  int HAN = 50;
  /** RegularExpression Id. */
  int IMD = 51;
  /** RegularExpression Id. */
  int IND = 52;
  /** RegularExpression Id. */
  int INP = 53;
  /** RegularExpression Id. */
  int LIN = 54;
  /** RegularExpression Id. */
  int LOC = 55;
  /** RegularExpression Id. */
  int MEA = 56;
  /** RegularExpression Id. */
  int MEM = 57;
  /** RegularExpression Id. */
  int MOA = 58;
  /** RegularExpression Id. */
  int NAD = 59;
  /** RegularExpression Id. */
  int PAC = 60;
  /** RegularExpression Id. */
  int PAI = 61;
  /** RegularExpression Id. */
  int PAT = 62;
  /** RegularExpression Id. */
  int PCD = 63;
  /** RegularExpression Id. */
  int PCI = 64;
  /** RegularExpression Id. */
  int PGI = 65;
  /** RegularExpression Id. */
  int PIA = 66;
  /** RegularExpression Id. */
  int PIT = 67;
  /** RegularExpression Id. */
  int PRC = 68;
  /** RegularExpression Id. */
  int PRI = 69;
  /** RegularExpression Id. */
  int PSD = 70;
  /** RegularExpression Id. */
  int QTY = 71;
  /** RegularExpression Id. */
  int QVA = 72;
  /** RegularExpression Id. */
  int QVR = 73;
  /** RegularExpression Id. */
  int RCS = 74;
  /** RegularExpression Id. */
  int REL = 75;
  /** RegularExpression Id. */
  int RFF = 76;
  /** RegularExpression Id. */
  int RNG = 77;
  /** RegularExpression Id. */
  int RTE = 78;
  /** RegularExpression Id. */
  int SCC = 79;
  /** RegularExpression Id. */
  int SEL = 80;
  /** RegularExpression Id. */
  int SEQ = 81;
  /** RegularExpression Id. */
  int SGP = 82;
  /** RegularExpression Id. */
  int SPS = 83;
  /** RegularExpression Id. */
  int STA = 84;
  /** RegularExpression Id. */
  int STS = 85;
  /** RegularExpression Id. */
  int TAX = 86;
  /** RegularExpression Id. */
  int TCC = 87;
  /** RegularExpression Id. */
  int TDT = 88;
  /** RegularExpression Id. */
  int TEM = 89;
  /** RegularExpression Id. */
  int TMD = 90;
  /** RegularExpression Id. */
  int TMP = 91;
  /** RegularExpression Id. */
  int TOD = 92;
  /** RegularExpression Id. */
  int TPL = 93;
  /** RegularExpression Id. */
  int TSR = 94;
  /** RegularExpression Id. */
  int UCD = 95;
  /** RegularExpression Id. */
  int UCF = 96;
  /** RegularExpression Id. */
  int UCI = 97;
  /** RegularExpression Id. */
  int UCM = 98;
  /** RegularExpression Id. */
  int UCS = 99;
  /** RegularExpression Id. */
  int UGH = 100;
  /** RegularExpression Id. */
  int UGT = 101;
  /** RegularExpression Id. */
  int UIB = 102;
  /** RegularExpression Id. */
  int UIH = 103;
  /** RegularExpression Id. */
  int UIR = 104;
  /** RegularExpression Id. */
  int UIT = 105;
  /** RegularExpression Id. */
  int UIZ = 106;
  /** RegularExpression Id. */
  int UNB = 107;
  /** RegularExpression Id. */
  int UNE = 108;
  /** RegularExpression Id. */
  int UNG = 109;
  /** RegularExpression Id. */
  int UNH = 110;
  /** RegularExpression Id. */
  int UNO = 111;
  /** RegularExpression Id. */
  int UNP = 112;
  /** RegularExpression Id. */
  int UNS = 113;
  /** RegularExpression Id. */
  int UNT = 114;
  /** RegularExpression Id. */
  int UNZ = 115;
  /** RegularExpression Id. */
  int USA = 116;
  /** RegularExpression Id. */
  int USB = 117;
  /** RegularExpression Id. */
  int USC = 118;
  /** RegularExpression Id. */
  int USD = 119;
  /** RegularExpression Id. */
  int USE = 120;
  /** RegularExpression Id. */
  int USF = 121;
  /** RegularExpression Id. */
  int USH = 122;
  /** RegularExpression Id. */
  int USL = 123;
  /** RegularExpression Id. */
  int USR = 124;
  /** RegularExpression Id. */
  int UST = 125;
  /** RegularExpression Id. */
  int USU = 126;
  /** RegularExpression Id. */
  int USX = 127;
  /** RegularExpression Id. */
  int USY = 128;
  /** RegularExpression Id. */
  int DATA = 129;
  /** RegularExpression Id. */
  int NUMBER = 130;
  /** RegularExpression Id. */
  int SEGTERM = 131;
  /** RegularExpression Id. */
  int DATASEP = 132;
  /** RegularExpression Id. */
  int COMPDATASEP = 133;
  /** RegularExpression Id. */
  int REPEATSEP = 134;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"AGR\"",
    "\"AJT\"",
    "\"ALC\"",
    "\"ALI\"",
    "\"API\"",
    "\"APR\"",
    "\"ARD\"",
    "\"ATT\"",
    "\"AUT\"",
    "\"BGM\"",
    "\"BII\"",
    "\"BUS\"",
    "\"CCI\"",
    "\"CNI\"",
    "\"CNT\"",
    "\"COM\"",
    "\"COT\"",
    "\"CPI\"",
    "\"CPS\"",
    "\"CST\"",
    "\"CTA\"",
    "\"CUX\"",
    "\"DGS\"",
    "\"DIM\"",
    "\"DLI\"",
    "\"DLM\"",
    "\"DMS\"",
    "\"DOC\"",
    "\"DTM\"",
    "\"EMP\"",
    "\"EQA\"",
    "\"EQD\"",
    "\"EQN\"",
    "\"ERC\"",
    "\"ERP\"",
    "\"FCA\"",
    "\"FII\"",
    "\"FTX\"",
    "\"GDS\"",
    "\"GID\"",
    "\"GIN\"",
    "\"GIR\"",
    "\"GIS\"",
    "\"GOR\"",
    "\"HAN\"",
    "\"IMD\"",
    "\"IND\"",
    "\"INP\"",
    "\"LIN\"",
    "\"LOC\"",
    "\"MEA\"",
    "\"MEM\"",
    "\"MOA\"",
    "\"NAD\"",
    "\"PAC\"",
    "\"PAI\"",
    "\"PAT\"",
    "\"PCD\"",
    "\"PCI\"",
    "\"PGI\"",
    "\"PIA\"",
    "\"PIT\"",
    "\"PRC\"",
    "\"PRI\"",
    "\"PSD\"",
    "\"QTY\"",
    "\"QVA\"",
    "\"QVR\"",
    "\"RCS\"",
    "\"REL\"",
    "\"RFF\"",
    "\"RNG\"",
    "\"RTE\"",
    "\"SCC\"",
    "\"SEL\"",
    "\"SEQ\"",
    "\"SGP\"",
    "\"SPS\"",
    "\"STA\"",
    "\"STS\"",
    "\"TAX\"",
    "\"TCC\"",
    "\"TDT\"",
    "\"TEM\"",
    "\"TMD\"",
    "\"TMP\"",
    "\"TOD\"",
    "\"TPL\"",
    "\"TSR\"",
    "\"UCD\"",
    "\"UCF\"",
    "\"UCI\"",
    "\"UCM\"",
    "\"UCS\"",
    "\"UGH\"",
    "\"UGT\"",
    "\"UIB\"",
    "\"UIH\"",
    "\"UIR\"",
    "\"UIT\"",
    "\"UIZ\"",
    "\"UNB\"",
    "\"UNE\"",
    "\"UNG\"",
    "\"UNH\"",
    "\"UNO\"",
    "\"UNP\"",
    "\"UNS\"",
    "\"UNT\"",
    "\"UNZ\"",
    "\"USA\"",
    "\"USB\"",
    "\"USC\"",
    "\"USD\"",
    "\"USE\"",
    "\"USF\"",
    "\"USH\"",
    "\"USL\"",
    "\"USR\"",
    "\"UST\"",
    "\"USU\"",
    "\"USX\"",
    "\"USY\"",
    "<DATA>",
    "<NUMBER>",
    "\"\\\'\"",
    "\"+\"",
    "\":\"",
    "\"*\"",
  };

}
