/* Generated By:JavaCC: Do not edit this line. D94BConstants.java */
package com.appliedmodels.edifact.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface D94BConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AGR = 6;
  /** RegularExpression Id. */
  int AJT = 7;
  /** RegularExpression Id. */
  int ALC = 8;
  /** RegularExpression Id. */
  int ALI = 9;
  /** RegularExpression Id. */
  int API = 10;
  /** RegularExpression Id. */
  int APR = 11;
  /** RegularExpression Id. */
  int ARD = 12;
  /** RegularExpression Id. */
  int ATT = 13;
  /** RegularExpression Id. */
  int AUT = 14;
  /** RegularExpression Id. */
  int BGM = 15;
  /** RegularExpression Id. */
  int BII = 16;
  /** RegularExpression Id. */
  int BUS = 17;
  /** RegularExpression Id. */
  int CCD = 18;
  /** RegularExpression Id. */
  int CCI = 19;
  /** RegularExpression Id. */
  int CNI = 20;
  /** RegularExpression Id. */
  int CNT = 21;
  /** RegularExpression Id. */
  int COM = 22;
  /** RegularExpression Id. */
  int COT = 23;
  /** RegularExpression Id. */
  int CPI = 24;
  /** RegularExpression Id. */
  int CPS = 25;
  /** RegularExpression Id. */
  int CST = 26;
  /** RegularExpression Id. */
  int CTA = 27;
  /** RegularExpression Id. */
  int CUX = 28;
  /** RegularExpression Id. */
  int DGS = 29;
  /** RegularExpression Id. */
  int DIM = 30;
  /** RegularExpression Id. */
  int DLI = 31;
  /** RegularExpression Id. */
  int DLM = 32;
  /** RegularExpression Id. */
  int DMS = 33;
  /** RegularExpression Id. */
  int DOC = 34;
  /** RegularExpression Id. */
  int DTM = 35;
  /** RegularExpression Id. */
  int EMP = 36;
  /** RegularExpression Id. */
  int EQA = 37;
  /** RegularExpression Id. */
  int EQD = 38;
  /** RegularExpression Id. */
  int EQN = 39;
  /** RegularExpression Id. */
  int ERC = 40;
  /** RegularExpression Id. */
  int ERP = 41;
  /** RegularExpression Id. */
  int FCA = 42;
  /** RegularExpression Id. */
  int FII = 43;
  /** RegularExpression Id. */
  int FTX = 44;
  /** RegularExpression Id. */
  int GDS = 45;
  /** RegularExpression Id. */
  int GID = 46;
  /** RegularExpression Id. */
  int GIN = 47;
  /** RegularExpression Id. */
  int GIR = 48;
  /** RegularExpression Id. */
  int GIS = 49;
  /** RegularExpression Id. */
  int GOR = 50;
  /** RegularExpression Id. */
  int HAN = 51;
  /** RegularExpression Id. */
  int ICD = 52;
  /** RegularExpression Id. */
  int IMD = 53;
  /** RegularExpression Id. */
  int IND = 54;
  /** RegularExpression Id. */
  int INP = 55;
  /** RegularExpression Id. */
  int INV = 56;
  /** RegularExpression Id. */
  int IRQ = 57;
  /** RegularExpression Id. */
  int LIN = 58;
  /** RegularExpression Id. */
  int LOC = 59;
  /** RegularExpression Id. */
  int MEA = 60;
  /** RegularExpression Id. */
  int MEM = 61;
  /** RegularExpression Id. */
  int MKS = 62;
  /** RegularExpression Id. */
  int MOA = 63;
  /** RegularExpression Id. */
  int NAD = 64;
  /** RegularExpression Id. */
  int PAC = 65;
  /** RegularExpression Id. */
  int PAI = 66;
  /** RegularExpression Id. */
  int PAT = 67;
  /** RegularExpression Id. */
  int PCD = 68;
  /** RegularExpression Id. */
  int PCI = 69;
  /** RegularExpression Id. */
  int PGI = 70;
  /** RegularExpression Id. */
  int PIA = 71;
  /** RegularExpression Id. */
  int PIT = 72;
  /** RegularExpression Id. */
  int PRC = 73;
  /** RegularExpression Id. */
  int PRI = 74;
  /** RegularExpression Id. */
  int PSD = 75;
  /** RegularExpression Id. */
  int QTY = 76;
  /** RegularExpression Id. */
  int QVA = 77;
  /** RegularExpression Id. */
  int QVR = 78;
  /** RegularExpression Id. */
  int RCS = 79;
  /** RegularExpression Id. */
  int REL = 80;
  /** RegularExpression Id. */
  int RFF = 81;
  /** RegularExpression Id. */
  int RNG = 82;
  /** RegularExpression Id. */
  int RTE = 83;
  /** RegularExpression Id. */
  int SCC = 84;
  /** RegularExpression Id. */
  int SEL = 85;
  /** RegularExpression Id. */
  int SEQ = 86;
  /** RegularExpression Id. */
  int SGP = 87;
  /** RegularExpression Id. */
  int SPS = 88;
  /** RegularExpression Id. */
  int STA = 89;
  /** RegularExpression Id. */
  int STG = 90;
  /** RegularExpression Id. */
  int STS = 91;
  /** RegularExpression Id. */
  int TAX = 92;
  /** RegularExpression Id. */
  int TCC = 93;
  /** RegularExpression Id. */
  int TDT = 94;
  /** RegularExpression Id. */
  int TEM = 95;
  /** RegularExpression Id. */
  int TMD = 96;
  /** RegularExpression Id. */
  int TMP = 97;
  /** RegularExpression Id. */
  int TOD = 98;
  /** RegularExpression Id. */
  int TPL = 99;
  /** RegularExpression Id. */
  int TSR = 100;
  /** RegularExpression Id. */
  int UCD = 101;
  /** RegularExpression Id. */
  int UCF = 102;
  /** RegularExpression Id. */
  int UCI = 103;
  /** RegularExpression Id. */
  int UCM = 104;
  /** RegularExpression Id. */
  int UCS = 105;
  /** RegularExpression Id. */
  int UGH = 106;
  /** RegularExpression Id. */
  int UGT = 107;
  /** RegularExpression Id. */
  int UIB = 108;
  /** RegularExpression Id. */
  int UIH = 109;
  /** RegularExpression Id. */
  int UIR = 110;
  /** RegularExpression Id. */
  int UIT = 111;
  /** RegularExpression Id. */
  int UIZ = 112;
  /** RegularExpression Id. */
  int UNB = 113;
  /** RegularExpression Id. */
  int UNE = 114;
  /** RegularExpression Id. */
  int UNG = 115;
  /** RegularExpression Id. */
  int UNH = 116;
  /** RegularExpression Id. */
  int UNO = 117;
  /** RegularExpression Id. */
  int UNP = 118;
  /** RegularExpression Id. */
  int UNS = 119;
  /** RegularExpression Id. */
  int UNT = 120;
  /** RegularExpression Id. */
  int UNZ = 121;
  /** RegularExpression Id. */
  int USA = 122;
  /** RegularExpression Id. */
  int USB = 123;
  /** RegularExpression Id. */
  int USC = 124;
  /** RegularExpression Id. */
  int USD = 125;
  /** RegularExpression Id. */
  int USE = 126;
  /** RegularExpression Id. */
  int USF = 127;
  /** RegularExpression Id. */
  int USH = 128;
  /** RegularExpression Id. */
  int USL = 129;
  /** RegularExpression Id. */
  int USR = 130;
  /** RegularExpression Id. */
  int UST = 131;
  /** RegularExpression Id. */
  int USU = 132;
  /** RegularExpression Id. */
  int USX = 133;
  /** RegularExpression Id. */
  int USY = 134;
  /** RegularExpression Id. */
  int DATA = 135;
  /** RegularExpression Id. */
  int NUMBER = 136;
  /** RegularExpression Id. */
  int SEGTERM = 137;
  /** RegularExpression Id. */
  int DATASEP = 138;
  /** RegularExpression Id. */
  int COMPDATASEP = 139;
  /** RegularExpression Id. */
  int REPEATSEP = 140;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"AGR\"",
    "\"AJT\"",
    "\"ALC\"",
    "\"ALI\"",
    "\"API\"",
    "\"APR\"",
    "\"ARD\"",
    "\"ATT\"",
    "\"AUT\"",
    "\"BGM\"",
    "\"BII\"",
    "\"BUS\"",
    "\"CCD\"",
    "\"CCI\"",
    "\"CNI\"",
    "\"CNT\"",
    "\"COM\"",
    "\"COT\"",
    "\"CPI\"",
    "\"CPS\"",
    "\"CST\"",
    "\"CTA\"",
    "\"CUX\"",
    "\"DGS\"",
    "\"DIM\"",
    "\"DLI\"",
    "\"DLM\"",
    "\"DMS\"",
    "\"DOC\"",
    "\"DTM\"",
    "\"EMP\"",
    "\"EQA\"",
    "\"EQD\"",
    "\"EQN\"",
    "\"ERC\"",
    "\"ERP\"",
    "\"FCA\"",
    "\"FII\"",
    "\"FTX\"",
    "\"GDS\"",
    "\"GID\"",
    "\"GIN\"",
    "\"GIR\"",
    "\"GIS\"",
    "\"GOR\"",
    "\"HAN\"",
    "\"ICD\"",
    "\"IMD\"",
    "\"IND\"",
    "\"INP\"",
    "\"INV\"",
    "\"IRQ\"",
    "\"LIN\"",
    "\"LOC\"",
    "\"MEA\"",
    "\"MEM\"",
    "\"MKS\"",
    "\"MOA\"",
    "\"NAD\"",
    "\"PAC\"",
    "\"PAI\"",
    "\"PAT\"",
    "\"PCD\"",
    "\"PCI\"",
    "\"PGI\"",
    "\"PIA\"",
    "\"PIT\"",
    "\"PRC\"",
    "\"PRI\"",
    "\"PSD\"",
    "\"QTY\"",
    "\"QVA\"",
    "\"QVR\"",
    "\"RCS\"",
    "\"REL\"",
    "\"RFF\"",
    "\"RNG\"",
    "\"RTE\"",
    "\"SCC\"",
    "\"SEL\"",
    "\"SEQ\"",
    "\"SGP\"",
    "\"SPS\"",
    "\"STA\"",
    "\"STG\"",
    "\"STS\"",
    "\"TAX\"",
    "\"TCC\"",
    "\"TDT\"",
    "\"TEM\"",
    "\"TMD\"",
    "\"TMP\"",
    "\"TOD\"",
    "\"TPL\"",
    "\"TSR\"",
    "\"UCD\"",
    "\"UCF\"",
    "\"UCI\"",
    "\"UCM\"",
    "\"UCS\"",
    "\"UGH\"",
    "\"UGT\"",
    "\"UIB\"",
    "\"UIH\"",
    "\"UIR\"",
    "\"UIT\"",
    "\"UIZ\"",
    "\"UNB\"",
    "\"UNE\"",
    "\"UNG\"",
    "\"UNH\"",
    "\"UNO\"",
    "\"UNP\"",
    "\"UNS\"",
    "\"UNT\"",
    "\"UNZ\"",
    "\"USA\"",
    "\"USB\"",
    "\"USC\"",
    "\"USD\"",
    "\"USE\"",
    "\"USF\"",
    "\"USH\"",
    "\"USL\"",
    "\"USR\"",
    "\"UST\"",
    "\"USU\"",
    "\"USX\"",
    "\"USY\"",
    "<DATA>",
    "<NUMBER>",
    "\"\\\'\"",
    "\"+\"",
    "\":\"",
    "\"*\"",
  };

}
