/* Generated By:JavaCC: Do not edit this line. D95AConstants.java */
package com.appliedmodels.edifact.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface D95AConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int AGR = 6;
  /** RegularExpression Id. */
  int AJT = 7;
  /** RegularExpression Id. */
  int ALC = 8;
  /** RegularExpression Id. */
  int ALI = 9;
  /** RegularExpression Id. */
  int API = 10;
  /** RegularExpression Id. */
  int APR = 11;
  /** RegularExpression Id. */
  int ARD = 12;
  /** RegularExpression Id. */
  int ARR = 13;
  /** RegularExpression Id. */
  int ASI = 14;
  /** RegularExpression Id. */
  int ATT = 15;
  /** RegularExpression Id. */
  int AUT = 16;
  /** RegularExpression Id. */
  int BGM = 17;
  /** RegularExpression Id. */
  int BII = 18;
  /** RegularExpression Id. */
  int BUS = 19;
  /** RegularExpression Id. */
  int CCD = 20;
  /** RegularExpression Id. */
  int CCI = 21;
  /** RegularExpression Id. */
  int CDV = 22;
  /** RegularExpression Id. */
  int CED = 23;
  /** RegularExpression Id. */
  int CNI = 24;
  /** RegularExpression Id. */
  int CNT = 25;
  /** RegularExpression Id. */
  int COD = 26;
  /** RegularExpression Id. */
  int COM = 27;
  /** RegularExpression Id. */
  int COT = 28;
  /** RegularExpression Id. */
  int CPI = 29;
  /** RegularExpression Id. */
  int CPS = 30;
  /** RegularExpression Id. */
  int CST = 31;
  /** RegularExpression Id. */
  int CTA = 32;
  /** RegularExpression Id. */
  int CUX = 33;
  /** RegularExpression Id. */
  int DAM = 34;
  /** RegularExpression Id. */
  int DGS = 35;
  /** RegularExpression Id. */
  int DIM = 36;
  /** RegularExpression Id. */
  int DLI = 37;
  /** RegularExpression Id. */
  int DLM = 38;
  /** RegularExpression Id. */
  int DMS = 39;
  /** RegularExpression Id. */
  int DOC = 40;
  /** RegularExpression Id. */
  int DSI = 41;
  /** RegularExpression Id. */
  int DTM = 42;
  /** RegularExpression Id. */
  int EFI = 43;
  /** RegularExpression Id. */
  int EMP = 44;
  /** RegularExpression Id. */
  int EQA = 45;
  /** RegularExpression Id. */
  int EQD = 46;
  /** RegularExpression Id. */
  int EQN = 47;
  /** RegularExpression Id. */
  int ERC = 48;
  /** RegularExpression Id. */
  int ERP = 49;
  /** RegularExpression Id. */
  int FCA = 50;
  /** RegularExpression Id. */
  int FII = 51;
  /** RegularExpression Id. */
  int FNS = 52;
  /** RegularExpression Id. */
  int FNT = 53;
  /** RegularExpression Id. */
  int FTX = 54;
  /** RegularExpression Id. */
  int GDS = 55;
  /** RegularExpression Id. */
  int GID = 56;
  /** RegularExpression Id. */
  int GIN = 57;
  /** RegularExpression Id. */
  int GIR = 58;
  /** RegularExpression Id. */
  int GIS = 59;
  /** RegularExpression Id. */
  int GOR = 60;
  /** RegularExpression Id. */
  int HAN = 61;
  /** RegularExpression Id. */
  int ICD = 62;
  /** RegularExpression Id. */
  int IDE = 63;
  /** RegularExpression Id. */
  int IMD = 64;
  /** RegularExpression Id. */
  int IND = 65;
  /** RegularExpression Id. */
  int INP = 66;
  /** RegularExpression Id. */
  int INV = 67;
  /** RegularExpression Id. */
  int IRQ = 68;
  /** RegularExpression Id. */
  int LIN = 69;
  /** RegularExpression Id. */
  int LOC = 70;
  /** RegularExpression Id. */
  int MEA = 71;
  /** RegularExpression Id. */
  int MEM = 72;
  /** RegularExpression Id. */
  int MKS = 73;
  /** RegularExpression Id. */
  int MOA = 74;
  /** RegularExpression Id. */
  int NAD = 75;
  /** RegularExpression Id. */
  int PAC = 76;
  /** RegularExpression Id. */
  int PAI = 77;
  /** RegularExpression Id. */
  int PAT = 78;
  /** RegularExpression Id. */
  int PCD = 79;
  /** RegularExpression Id. */
  int PCI = 80;
  /** RegularExpression Id. */
  int PGI = 81;
  /** RegularExpression Id. */
  int PIA = 82;
  /** RegularExpression Id. */
  int PIT = 83;
  /** RegularExpression Id. */
  int PRC = 84;
  /** RegularExpression Id. */
  int PRI = 85;
  /** RegularExpression Id. */
  int PSD = 86;
  /** RegularExpression Id. */
  int QTY = 87;
  /** RegularExpression Id. */
  int QVA = 88;
  /** RegularExpression Id. */
  int QVR = 89;
  /** RegularExpression Id. */
  int RCS = 90;
  /** RegularExpression Id. */
  int REL = 91;
  /** RegularExpression Id. */
  int RFF = 92;
  /** RegularExpression Id. */
  int RNG = 93;
  /** RegularExpression Id. */
  int RTE = 94;
  /** RegularExpression Id. */
  int SCC = 95;
  /** RegularExpression Id. */
  int SCD = 96;
  /** RegularExpression Id. */
  int SEL = 97;
  /** RegularExpression Id. */
  int SEQ = 98;
  /** RegularExpression Id. */
  int SGP = 99;
  /** RegularExpression Id. */
  int SPS = 100;
  /** RegularExpression Id. */
  int STA = 101;
  /** RegularExpression Id. */
  int STC = 102;
  /** RegularExpression Id. */
  int STG = 103;
  /** RegularExpression Id. */
  int STS = 104;
  /** RegularExpression Id. */
  int TAX = 105;
  /** RegularExpression Id. */
  int TCC = 106;
  /** RegularExpression Id. */
  int TDT = 107;
  /** RegularExpression Id. */
  int TEM = 108;
  /** RegularExpression Id. */
  int TMD = 109;
  /** RegularExpression Id. */
  int TMP = 110;
  /** RegularExpression Id. */
  int TOD = 111;
  /** RegularExpression Id. */
  int TPL = 112;
  /** RegularExpression Id. */
  int TSR = 113;
  /** RegularExpression Id. */
  int VLI = 114;
  /** RegularExpression Id. */
  int UCD = 115;
  /** RegularExpression Id. */
  int UCF = 116;
  /** RegularExpression Id. */
  int UCI = 117;
  /** RegularExpression Id. */
  int UCM = 118;
  /** RegularExpression Id. */
  int UCS = 119;
  /** RegularExpression Id. */
  int UGH = 120;
  /** RegularExpression Id. */
  int UGT = 121;
  /** RegularExpression Id. */
  int UIB = 122;
  /** RegularExpression Id. */
  int UIH = 123;
  /** RegularExpression Id. */
  int UIR = 124;
  /** RegularExpression Id. */
  int UIT = 125;
  /** RegularExpression Id. */
  int UIZ = 126;
  /** RegularExpression Id. */
  int UNB = 127;
  /** RegularExpression Id. */
  int UNE = 128;
  /** RegularExpression Id. */
  int UNG = 129;
  /** RegularExpression Id. */
  int UNH = 130;
  /** RegularExpression Id. */
  int UNO = 131;
  /** RegularExpression Id. */
  int UNP = 132;
  /** RegularExpression Id. */
  int UNS = 133;
  /** RegularExpression Id. */
  int UNT = 134;
  /** RegularExpression Id. */
  int UNZ = 135;
  /** RegularExpression Id. */
  int USA = 136;
  /** RegularExpression Id. */
  int USB = 137;
  /** RegularExpression Id. */
  int USC = 138;
  /** RegularExpression Id. */
  int USD = 139;
  /** RegularExpression Id. */
  int USE = 140;
  /** RegularExpression Id. */
  int USF = 141;
  /** RegularExpression Id. */
  int USH = 142;
  /** RegularExpression Id. */
  int USL = 143;
  /** RegularExpression Id. */
  int USR = 144;
  /** RegularExpression Id. */
  int UST = 145;
  /** RegularExpression Id. */
  int USU = 146;
  /** RegularExpression Id. */
  int USX = 147;
  /** RegularExpression Id. */
  int USY = 148;
  /** RegularExpression Id. */
  int DATA = 149;
  /** RegularExpression Id. */
  int NUMBER = 150;
  /** RegularExpression Id. */
  int SEGTERM = 151;
  /** RegularExpression Id. */
  int DATASEP = 152;
  /** RegularExpression Id. */
  int COMPDATASEP = 153;
  /** RegularExpression Id. */
  int REPEATSEP = 154;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"AGR\"",
    "\"AJT\"",
    "\"ALC\"",
    "\"ALI\"",
    "\"API\"",
    "\"APR\"",
    "\"ARD\"",
    "\"ARR\"",
    "\"ASI\"",
    "\"ATT\"",
    "\"AUT\"",
    "\"BGM\"",
    "\"BII\"",
    "\"BUS\"",
    "\"CCD\"",
    "\"CCI\"",
    "\"CDV\"",
    "\"CED\"",
    "\"CNI\"",
    "\"CNT\"",
    "\"COD\"",
    "\"COM\"",
    "\"COT\"",
    "\"CPI\"",
    "\"CPS\"",
    "\"CST\"",
    "\"CTA\"",
    "\"CUX\"",
    "\"DAM\"",
    "\"DGS\"",
    "\"DIM\"",
    "\"DLI\"",
    "\"DLM\"",
    "\"DMS\"",
    "\"DOC\"",
    "\"DSI\"",
    "\"DTM\"",
    "\"EFI\"",
    "\"EMP\"",
    "\"EQA\"",
    "\"EQD\"",
    "\"EQN\"",
    "\"ERC\"",
    "\"ERP\"",
    "\"FCA\"",
    "\"FII\"",
    "\"FNS\"",
    "\"FNT\"",
    "\"FTX\"",
    "\"GDS\"",
    "\"GID\"",
    "\"GIN\"",
    "\"GIR\"",
    "\"GIS\"",
    "\"GOR\"",
    "\"HAN\"",
    "\"ICD\"",
    "\"IDE\"",
    "\"IMD\"",
    "\"IND\"",
    "\"INP\"",
    "\"INV\"",
    "\"IRQ\"",
    "\"LIN\"",
    "\"LOC\"",
    "\"MEA\"",
    "\"MEM\"",
    "\"MKS\"",
    "\"MOA\"",
    "\"NAD\"",
    "\"PAC\"",
    "\"PAI\"",
    "\"PAT\"",
    "\"PCD\"",
    "\"PCI\"",
    "\"PGI\"",
    "\"PIA\"",
    "\"PIT\"",
    "\"PRC\"",
    "\"PRI\"",
    "\"PSD\"",
    "\"QTY\"",
    "\"QVA\"",
    "\"QVR\"",
    "\"RCS\"",
    "\"REL\"",
    "\"RFF\"",
    "\"RNG\"",
    "\"RTE\"",
    "\"SCC\"",
    "\"SCD\"",
    "\"SEL\"",
    "\"SEQ\"",
    "\"SGP\"",
    "\"SPS\"",
    "\"STA\"",
    "\"STC\"",
    "\"STG\"",
    "\"STS\"",
    "\"TAX\"",
    "\"TCC\"",
    "\"TDT\"",
    "\"TEM\"",
    "\"TMD\"",
    "\"TMP\"",
    "\"TOD\"",
    "\"TPL\"",
    "\"TSR\"",
    "\"VLI\"",
    "\"UCD\"",
    "\"UCF\"",
    "\"UCI\"",
    "\"UCM\"",
    "\"UCS\"",
    "\"UGH\"",
    "\"UGT\"",
    "\"UIB\"",
    "\"UIH\"",
    "\"UIR\"",
    "\"UIT\"",
    "\"UIZ\"",
    "\"UNB\"",
    "\"UNE\"",
    "\"UNG\"",
    "\"UNH\"",
    "\"UNO\"",
    "\"UNP\"",
    "\"UNS\"",
    "\"UNT\"",
    "\"UNZ\"",
    "\"USA\"",
    "\"USB\"",
    "\"USC\"",
    "\"USD\"",
    "\"USE\"",
    "\"USF\"",
    "\"USH\"",
    "\"USL\"",
    "\"USR\"",
    "\"UST\"",
    "\"USU\"",
    "\"USX\"",
    "\"USY\"",
    "<DATA>",
    "<NUMBER>",
    "\"\\\'\"",
    "\"+\"",
    "\":\"",
    "\"*\"",
  };

}
