/* Generated By:JavaCC: Do not edit this line. D95BConstants.java */
package com.appliedmodels.edifact.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface D95BConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADR = 6;
  /** RegularExpression Id. */
  int AGR = 7;
  /** RegularExpression Id. */
  int AJT = 8;
  /** RegularExpression Id. */
  int ALC = 9;
  /** RegularExpression Id. */
  int ALI = 10;
  /** RegularExpression Id. */
  int APR = 11;
  /** RegularExpression Id. */
  int ARD = 12;
  /** RegularExpression Id. */
  int ARR = 13;
  /** RegularExpression Id. */
  int ASI = 14;
  /** RegularExpression Id. */
  int ATT = 15;
  /** RegularExpression Id. */
  int AUT = 16;
  /** RegularExpression Id. */
  int BGM = 17;
  /** RegularExpression Id. */
  int BII = 18;
  /** RegularExpression Id. */
  int BUS = 19;
  /** RegularExpression Id. */
  int CAV = 20;
  /** RegularExpression Id. */
  int CCD = 21;
  /** RegularExpression Id. */
  int CCI = 22;
  /** RegularExpression Id. */
  int CDS = 23;
  /** RegularExpression Id. */
  int CDV = 24;
  /** RegularExpression Id. */
  int CED = 25;
  /** RegularExpression Id. */
  int CMP = 26;
  /** RegularExpression Id. */
  int CNI = 27;
  /** RegularExpression Id. */
  int CNT = 28;
  /** RegularExpression Id. */
  int COD = 29;
  /** RegularExpression Id. */
  int COM = 30;
  /** RegularExpression Id. */
  int COT = 31;
  /** RegularExpression Id. */
  int CPI = 32;
  /** RegularExpression Id. */
  int CPS = 33;
  /** RegularExpression Id. */
  int CST = 34;
  /** RegularExpression Id. */
  int CTA = 35;
  /** RegularExpression Id. */
  int CUX = 36;
  /** RegularExpression Id. */
  int DAM = 37;
  /** RegularExpression Id. */
  int DGS = 38;
  /** RegularExpression Id. */
  int DII = 39;
  /** RegularExpression Id. */
  int DIM = 40;
  /** RegularExpression Id. */
  int DLI = 41;
  /** RegularExpression Id. */
  int DLM = 42;
  /** RegularExpression Id. */
  int DMS = 43;
  /** RegularExpression Id. */
  int DOC = 44;
  /** RegularExpression Id. */
  int DSI = 45;
  /** RegularExpression Id. */
  int DTM = 46;
  /** RegularExpression Id. */
  int EFI = 47;
  /** RegularExpression Id. */
  int ELM = 48;
  /** RegularExpression Id. */
  int ELU = 49;
  /** RegularExpression Id. */
  int EMP = 50;
  /** RegularExpression Id. */
  int EQA = 51;
  /** RegularExpression Id. */
  int EQD = 52;
  /** RegularExpression Id. */
  int EQN = 53;
  /** RegularExpression Id. */
  int ERC = 54;
  /** RegularExpression Id. */
  int ERP = 55;
  /** RegularExpression Id. */
  int FCA = 56;
  /** RegularExpression Id. */
  int FII = 57;
  /** RegularExpression Id. */
  int FNS = 58;
  /** RegularExpression Id. */
  int FNT = 59;
  /** RegularExpression Id. */
  int FTX = 60;
  /** RegularExpression Id. */
  int GDS = 61;
  /** RegularExpression Id. */
  int GID = 62;
  /** RegularExpression Id. */
  int GIN = 63;
  /** RegularExpression Id. */
  int GIR = 64;
  /** RegularExpression Id. */
  int GIS = 65;
  /** RegularExpression Id. */
  int GOR = 66;
  /** RegularExpression Id. */
  int GRU = 67;
  /** RegularExpression Id. */
  int HAN = 68;
  /** RegularExpression Id. */
  int ICD = 69;
  /** RegularExpression Id. */
  int IDE = 70;
  /** RegularExpression Id. */
  int IHC = 71;
  /** RegularExpression Id. */
  int IMD = 72;
  /** RegularExpression Id. */
  int IND = 73;
  /** RegularExpression Id. */
  int INP = 74;
  /** RegularExpression Id. */
  int INV = 75;
  /** RegularExpression Id. */
  int IRQ = 76;
  /** RegularExpression Id. */
  int LAN = 77;
  /** RegularExpression Id. */
  int LIN = 78;
  /** RegularExpression Id. */
  int LOC = 79;
  /** RegularExpression Id. */
  int MEA = 80;
  /** RegularExpression Id. */
  int MEM = 81;
  /** RegularExpression Id. */
  int MKS = 82;
  /** RegularExpression Id. */
  int MOA = 83;
  /** RegularExpression Id. */
  int MSG = 84;
  /** RegularExpression Id. */
  int NAD = 85;
  /** RegularExpression Id. */
  int NAT = 86;
  /** RegularExpression Id. */
  int PAC = 87;
  /** RegularExpression Id. */
  int PAI = 88;
  /** RegularExpression Id. */
  int PAT = 89;
  /** RegularExpression Id. */
  int PCD = 90;
  /** RegularExpression Id. */
  int PCI = 91;
  /** RegularExpression Id. */
  int PDI = 92;
  /** RegularExpression Id. */
  int PGI = 93;
  /** RegularExpression Id. */
  int PIA = 94;
  /** RegularExpression Id. */
  int PIT = 95;
  /** RegularExpression Id. */
  int PNA = 96;
  /** RegularExpression Id. */
  int PRC = 97;
  /** RegularExpression Id. */
  int PRI = 98;
  /** RegularExpression Id. */
  int PSD = 99;
  /** RegularExpression Id. */
  int PTY = 100;
  /** RegularExpression Id. */
  int QTY = 101;
  /** RegularExpression Id. */
  int QVR = 102;
  /** RegularExpression Id. */
  int RCS = 103;
  /** RegularExpression Id. */
  int REL = 104;
  /** RegularExpression Id. */
  int RFF = 105;
  /** RegularExpression Id. */
  int RNG = 106;
  /** RegularExpression Id. */
  int RTE = 107;
  /** RegularExpression Id. */
  int SAL = 108;
  /** RegularExpression Id. */
  int SCC = 109;
  /** RegularExpression Id. */
  int SCD = 110;
  /** RegularExpression Id. */
  int SEG = 111;
  /** RegularExpression Id. */
  int SEL = 112;
  /** RegularExpression Id. */
  int SEQ = 113;
  /** RegularExpression Id. */
  int SFI = 114;
  /** RegularExpression Id. */
  int SGP = 115;
  /** RegularExpression Id. */
  int SGU = 116;
  /** RegularExpression Id. */
  int SPS = 117;
  /** RegularExpression Id. */
  int STA = 118;
  /** RegularExpression Id. */
  int STC = 119;
  /** RegularExpression Id. */
  int STG = 120;
  /** RegularExpression Id. */
  int STS = 121;
  /** RegularExpression Id. */
  int TAX = 122;
  /** RegularExpression Id. */
  int TCC = 123;
  /** RegularExpression Id. */
  int TDT = 124;
  /** RegularExpression Id. */
  int TEM = 125;
  /** RegularExpression Id. */
  int TMD = 126;
  /** RegularExpression Id. */
  int TMP = 127;
  /** RegularExpression Id. */
  int TOD = 128;
  /** RegularExpression Id. */
  int TPL = 129;
  /** RegularExpression Id. */
  int TSR = 130;
  /** RegularExpression Id. */
  int VLI = 131;
  /** RegularExpression Id. */
  int UCD = 132;
  /** RegularExpression Id. */
  int UCF = 133;
  /** RegularExpression Id. */
  int UCI = 134;
  /** RegularExpression Id. */
  int UCM = 135;
  /** RegularExpression Id. */
  int UCS = 136;
  /** RegularExpression Id. */
  int UGH = 137;
  /** RegularExpression Id. */
  int UGT = 138;
  /** RegularExpression Id. */
  int UIB = 139;
  /** RegularExpression Id. */
  int UIH = 140;
  /** RegularExpression Id. */
  int UIR = 141;
  /** RegularExpression Id. */
  int UIT = 142;
  /** RegularExpression Id. */
  int UIZ = 143;
  /** RegularExpression Id. */
  int UNB = 144;
  /** RegularExpression Id. */
  int UNE = 145;
  /** RegularExpression Id. */
  int UNG = 146;
  /** RegularExpression Id. */
  int UNH = 147;
  /** RegularExpression Id. */
  int UNO = 148;
  /** RegularExpression Id. */
  int UNP = 149;
  /** RegularExpression Id. */
  int UNS = 150;
  /** RegularExpression Id. */
  int UNT = 151;
  /** RegularExpression Id. */
  int UNZ = 152;
  /** RegularExpression Id. */
  int USA = 153;
  /** RegularExpression Id. */
  int USB = 154;
  /** RegularExpression Id. */
  int USC = 155;
  /** RegularExpression Id. */
  int USD = 156;
  /** RegularExpression Id. */
  int USE = 157;
  /** RegularExpression Id. */
  int USF = 158;
  /** RegularExpression Id. */
  int USH = 159;
  /** RegularExpression Id. */
  int USL = 160;
  /** RegularExpression Id. */
  int USR = 161;
  /** RegularExpression Id. */
  int UST = 162;
  /** RegularExpression Id. */
  int USU = 163;
  /** RegularExpression Id. */
  int USX = 164;
  /** RegularExpression Id. */
  int USY = 165;
  /** RegularExpression Id. */
  int DATA = 166;
  /** RegularExpression Id. */
  int NUMBER = 167;
  /** RegularExpression Id. */
  int SEGTERM = 168;
  /** RegularExpression Id. */
  int DATASEP = 169;
  /** RegularExpression Id. */
  int COMPDATASEP = 170;
  /** RegularExpression Id. */
  int REPEATSEP = 171;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"ADR\"",
    "\"AGR\"",
    "\"AJT\"",
    "\"ALC\"",
    "\"ALI\"",
    "\"APR\"",
    "\"ARD\"",
    "\"ARR\"",
    "\"ASI\"",
    "\"ATT\"",
    "\"AUT\"",
    "\"BGM\"",
    "\"BII\"",
    "\"BUS\"",
    "\"CAV\"",
    "\"CCD\"",
    "\"CCI\"",
    "\"CDS\"",
    "\"CDV\"",
    "\"CED\"",
    "\"CMP\"",
    "\"CNI\"",
    "\"CNT\"",
    "\"COD\"",
    "\"COM\"",
    "\"COT\"",
    "\"CPI\"",
    "\"CPS\"",
    "\"CST\"",
    "\"CTA\"",
    "\"CUX\"",
    "\"DAM\"",
    "\"DGS\"",
    "\"DII\"",
    "\"DIM\"",
    "\"DLI\"",
    "\"DLM\"",
    "\"DMS\"",
    "\"DOC\"",
    "\"DSI\"",
    "\"DTM\"",
    "\"EFI\"",
    "\"ELM\"",
    "\"ELU\"",
    "\"EMP\"",
    "\"EQA\"",
    "\"EQD\"",
    "\"EQN\"",
    "\"ERC\"",
    "\"ERP\"",
    "\"FCA\"",
    "\"FII\"",
    "\"FNS\"",
    "\"FNT\"",
    "\"FTX\"",
    "\"GDS\"",
    "\"GID\"",
    "\"GIN\"",
    "\"GIR\"",
    "\"GIS\"",
    "\"GOR\"",
    "\"GRU\"",
    "\"HAN\"",
    "\"ICD\"",
    "\"IDE\"",
    "\"IHC\"",
    "\"IMD\"",
    "\"IND\"",
    "\"INP\"",
    "\"INV\"",
    "\"IRQ\"",
    "\"LAN\"",
    "\"LIN\"",
    "\"LOC\"",
    "\"MEA\"",
    "\"MEM\"",
    "\"MKS\"",
    "\"MOA\"",
    "\"MSG\"",
    "\"NAD\"",
    "\"NAT\"",
    "\"PAC\"",
    "\"PAI\"",
    "\"PAT\"",
    "\"PCD\"",
    "\"PCI\"",
    "\"PDI\"",
    "\"PGI\"",
    "\"PIA\"",
    "\"PIT\"",
    "\"PNA\"",
    "\"PRC\"",
    "\"PRI\"",
    "\"PSD\"",
    "\"PTY\"",
    "\"QTY\"",
    "\"QVR\"",
    "\"RCS\"",
    "\"REL\"",
    "\"RFF\"",
    "\"RNG\"",
    "\"RTE\"",
    "\"SAL\"",
    "\"SCC\"",
    "\"SCD\"",
    "\"SEG\"",
    "\"SEL\"",
    "\"SEQ\"",
    "\"SFI\"",
    "\"SGP\"",
    "\"SGU\"",
    "\"SPS\"",
    "\"STA\"",
    "\"STC\"",
    "\"STG\"",
    "\"STS\"",
    "\"TAX\"",
    "\"TCC\"",
    "\"TDT\"",
    "\"TEM\"",
    "\"TMD\"",
    "\"TMP\"",
    "\"TOD\"",
    "\"TPL\"",
    "\"TSR\"",
    "\"VLI\"",
    "\"UCD\"",
    "\"UCF\"",
    "\"UCI\"",
    "\"UCM\"",
    "\"UCS\"",
    "\"UGH\"",
    "\"UGT\"",
    "\"UIB\"",
    "\"UIH\"",
    "\"UIR\"",
    "\"UIT\"",
    "\"UIZ\"",
    "\"UNB\"",
    "\"UNE\"",
    "\"UNG\"",
    "\"UNH\"",
    "\"UNO\"",
    "\"UNP\"",
    "\"UNS\"",
    "\"UNT\"",
    "\"UNZ\"",
    "\"USA\"",
    "\"USB\"",
    "\"USC\"",
    "\"USD\"",
    "\"USE\"",
    "\"USF\"",
    "\"USH\"",
    "\"USL\"",
    "\"USR\"",
    "\"UST\"",
    "\"USU\"",
    "\"USX\"",
    "\"USY\"",
    "<DATA>",
    "<NUMBER>",
    "\"\\\'\"",
    "\"+\"",
    "\":\"",
    "\"*\"",
  };

}
