/* Generated By:JavaCC: Do not edit this line. D96BConstants.java */
package com.appliedmodels.edifact.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface D96BConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADR = 6;
  /** RegularExpression Id. */
  int AGR = 7;
  /** RegularExpression Id. */
  int AJT = 8;
  /** RegularExpression Id. */
  int ALC = 9;
  /** RegularExpression Id. */
  int ALI = 10;
  /** RegularExpression Id. */
  int APR = 11;
  /** RegularExpression Id. */
  int ARD = 12;
  /** RegularExpression Id. */
  int ARR = 13;
  /** RegularExpression Id. */
  int ASI = 14;
  /** RegularExpression Id. */
  int ATT = 15;
  /** RegularExpression Id. */
  int AUT = 16;
  /** RegularExpression Id. */
  int BGM = 17;
  /** RegularExpression Id. */
  int BII = 18;
  /** RegularExpression Id. */
  int BUS = 19;
  /** RegularExpression Id. */
  int CAV = 20;
  /** RegularExpression Id. */
  int CCD = 21;
  /** RegularExpression Id. */
  int CCI = 22;
  /** RegularExpression Id. */
  int CDI = 23;
  /** RegularExpression Id. */
  int CDS = 24;
  /** RegularExpression Id. */
  int CDV = 25;
  /** RegularExpression Id. */
  int CED = 26;
  /** RegularExpression Id. */
  int CIN = 27;
  /** RegularExpression Id. */
  int CLI = 28;
  /** RegularExpression Id. */
  int CMP = 29;
  /** RegularExpression Id. */
  int CNI = 30;
  /** RegularExpression Id. */
  int CNT = 31;
  /** RegularExpression Id. */
  int COD = 32;
  /** RegularExpression Id. */
  int COM = 33;
  /** RegularExpression Id. */
  int COT = 34;
  /** RegularExpression Id. */
  int CPI = 35;
  /** RegularExpression Id. */
  int CPS = 36;
  /** RegularExpression Id. */
  int CST = 37;
  /** RegularExpression Id. */
  int CTA = 38;
  /** RegularExpression Id. */
  int CUX = 39;
  /** RegularExpression Id. */
  int DAM = 40;
  /** RegularExpression Id. */
  int DGS = 41;
  /** RegularExpression Id. */
  int DII = 42;
  /** RegularExpression Id. */
  int DIM = 43;
  /** RegularExpression Id. */
  int DLI = 44;
  /** RegularExpression Id. */
  int DLM = 45;
  /** RegularExpression Id. */
  int DMS = 46;
  /** RegularExpression Id. */
  int DOC = 47;
  /** RegularExpression Id. */
  int DSG = 48;
  /** RegularExpression Id. */
  int DSI = 49;
  /** RegularExpression Id. */
  int DTM = 50;
  /** RegularExpression Id. */
  int EFI = 51;
  /** RegularExpression Id. */
  int ELM = 52;
  /** RegularExpression Id. */
  int ELU = 53;
  /** RegularExpression Id. */
  int EMP = 54;
  /** RegularExpression Id. */
  int EQA = 55;
  /** RegularExpression Id. */
  int EQD = 56;
  /** RegularExpression Id. */
  int EQN = 57;
  /** RegularExpression Id. */
  int ERC = 58;
  /** RegularExpression Id. */
  int ERP = 59;
  /** RegularExpression Id. */
  int FCA = 60;
  /** RegularExpression Id. */
  int FII = 61;
  /** RegularExpression Id. */
  int FNS = 62;
  /** RegularExpression Id. */
  int FNT = 63;
  /** RegularExpression Id. */
  int FTX = 64;
  /** RegularExpression Id. */
  int GDS = 65;
  /** RegularExpression Id. */
  int GID = 66;
  /** RegularExpression Id. */
  int GIN = 67;
  /** RegularExpression Id. */
  int GIR = 68;
  /** RegularExpression Id. */
  int GIS = 69;
  /** RegularExpression Id. */
  int GOR = 70;
  /** RegularExpression Id. */
  int GRU = 71;
  /** RegularExpression Id. */
  int HAN = 72;
  /** RegularExpression Id. */
  int HYN = 73;
  /** RegularExpression Id. */
  int ICD = 74;
  /** RegularExpression Id. */
  int IDE = 75;
  /** RegularExpression Id. */
  int IHC = 76;
  /** RegularExpression Id. */
  int IMD = 77;
  /** RegularExpression Id. */
  int IND = 78;
  /** RegularExpression Id. */
  int INP = 79;
  /** RegularExpression Id. */
  int INV = 80;
  /** RegularExpression Id. */
  int IRQ = 81;
  /** RegularExpression Id. */
  int LAN = 82;
  /** RegularExpression Id. */
  int LIN = 83;
  /** RegularExpression Id. */
  int LOC = 84;
  /** RegularExpression Id. */
  int MEA = 85;
  /** RegularExpression Id. */
  int MEM = 86;
  /** RegularExpression Id. */
  int MKS = 87;
  /** RegularExpression Id. */
  int MOA = 88;
  /** RegularExpression Id. */
  int MSG = 89;
  /** RegularExpression Id. */
  int NAD = 90;
  /** RegularExpression Id. */
  int NAT = 91;
  /** RegularExpression Id. */
  int PAC = 92;
  /** RegularExpression Id. */
  int PAI = 93;
  /** RegularExpression Id. */
  int PAS = 94;
  /** RegularExpression Id. */
  int PAT = 95;
  /** RegularExpression Id. */
  int PCD = 96;
  /** RegularExpression Id. */
  int PCI = 97;
  /** RegularExpression Id. */
  int PDI = 98;
  /** RegularExpression Id. */
  int PGI = 99;
  /** RegularExpression Id. */
  int PIA = 100;
  /** RegularExpression Id. */
  int PIT = 101;
  /** RegularExpression Id. */
  int PNA = 102;
  /** RegularExpression Id. */
  int PRC = 103;
  /** RegularExpression Id. */
  int PRI = 104;
  /** RegularExpression Id. */
  int PSD = 105;
  /** RegularExpression Id. */
  int PTY = 106;
  /** RegularExpression Id. */
  int QTY = 107;
  /** RegularExpression Id. */
  int QUA = 108;
  /** RegularExpression Id. */
  int QVR = 109;
  /** RegularExpression Id. */
  int RCS = 110;
  /** RegularExpression Id. */
  int REL = 111;
  /** RegularExpression Id. */
  int RFF = 112;
  /** RegularExpression Id. */
  int RNG = 113;
  /** RegularExpression Id. */
  int RSL = 114;
  /** RegularExpression Id. */
  int RTE = 115;
  /** RegularExpression Id. */
  int SAL = 116;
  /** RegularExpression Id. */
  int SCC = 117;
  /** RegularExpression Id. */
  int SCD = 118;
  /** RegularExpression Id. */
  int SEG = 119;
  /** RegularExpression Id. */
  int SEL = 120;
  /** RegularExpression Id. */
  int SEQ = 121;
  /** RegularExpression Id. */
  int SFI = 122;
  /** RegularExpression Id. */
  int SGP = 123;
  /** RegularExpression Id. */
  int SGU = 124;
  /** RegularExpression Id. */
  int SPR = 125;
  /** RegularExpression Id. */
  int SPS = 126;
  /** RegularExpression Id. */
  int STA = 127;
  /** RegularExpression Id. */
  int STC = 128;
  /** RegularExpression Id. */
  int STG = 129;
  /** RegularExpression Id. */
  int STS = 130;
  /** RegularExpression Id. */
  int TAX = 131;
  /** RegularExpression Id. */
  int TCC = 132;
  /** RegularExpression Id. */
  int TDT = 133;
  /** RegularExpression Id. */
  int TEM = 134;
  /** RegularExpression Id. */
  int TMD = 135;
  /** RegularExpression Id. */
  int TMP = 136;
  /** RegularExpression Id. */
  int TOD = 137;
  /** RegularExpression Id. */
  int TPL = 138;
  /** RegularExpression Id. */
  int TRU = 139;
  /** RegularExpression Id. */
  int TSR = 140;
  /** RegularExpression Id. */
  int VLI = 141;
  /** RegularExpression Id. */
  int UCD = 142;
  /** RegularExpression Id. */
  int UCF = 143;
  /** RegularExpression Id. */
  int UCI = 144;
  /** RegularExpression Id. */
  int UCM = 145;
  /** RegularExpression Id. */
  int UCS = 146;
  /** RegularExpression Id. */
  int UGH = 147;
  /** RegularExpression Id. */
  int UGT = 148;
  /** RegularExpression Id. */
  int UIB = 149;
  /** RegularExpression Id. */
  int UIH = 150;
  /** RegularExpression Id. */
  int UIR = 151;
  /** RegularExpression Id. */
  int UIT = 152;
  /** RegularExpression Id. */
  int UIZ = 153;
  /** RegularExpression Id. */
  int UNB = 154;
  /** RegularExpression Id. */
  int UNE = 155;
  /** RegularExpression Id. */
  int UNG = 156;
  /** RegularExpression Id. */
  int UNH = 157;
  /** RegularExpression Id. */
  int UNO = 158;
  /** RegularExpression Id. */
  int UNP = 159;
  /** RegularExpression Id. */
  int UNS = 160;
  /** RegularExpression Id. */
  int UNT = 161;
  /** RegularExpression Id. */
  int UNZ = 162;
  /** RegularExpression Id. */
  int USA = 163;
  /** RegularExpression Id. */
  int USB = 164;
  /** RegularExpression Id. */
  int USC = 165;
  /** RegularExpression Id. */
  int USD = 166;
  /** RegularExpression Id. */
  int USE = 167;
  /** RegularExpression Id. */
  int USF = 168;
  /** RegularExpression Id. */
  int USH = 169;
  /** RegularExpression Id. */
  int USL = 170;
  /** RegularExpression Id. */
  int USR = 171;
  /** RegularExpression Id. */
  int UST = 172;
  /** RegularExpression Id. */
  int USU = 173;
  /** RegularExpression Id. */
  int USX = 174;
  /** RegularExpression Id. */
  int USY = 175;
  /** RegularExpression Id. */
  int DATA = 176;
  /** RegularExpression Id. */
  int NUMBER = 177;
  /** RegularExpression Id. */
  int SEGTERM = 178;
  /** RegularExpression Id. */
  int DATASEP = 179;
  /** RegularExpression Id. */
  int COMPDATASEP = 180;
  /** RegularExpression Id. */
  int REPEATSEP = 181;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"ADR\"",
    "\"AGR\"",
    "\"AJT\"",
    "\"ALC\"",
    "\"ALI\"",
    "\"APR\"",
    "\"ARD\"",
    "\"ARR\"",
    "\"ASI\"",
    "\"ATT\"",
    "\"AUT\"",
    "\"BGM\"",
    "\"BII\"",
    "\"BUS\"",
    "\"CAV\"",
    "\"CCD\"",
    "\"CCI\"",
    "\"CDI\"",
    "\"CDS\"",
    "\"CDV\"",
    "\"CED\"",
    "\"CIN\"",
    "\"CLI\"",
    "\"CMP\"",
    "\"CNI\"",
    "\"CNT\"",
    "\"COD\"",
    "\"COM\"",
    "\"COT\"",
    "\"CPI\"",
    "\"CPS\"",
    "\"CST\"",
    "\"CTA\"",
    "\"CUX\"",
    "\"DAM\"",
    "\"DGS\"",
    "\"DII\"",
    "\"DIM\"",
    "\"DLI\"",
    "\"DLM\"",
    "\"DMS\"",
    "\"DOC\"",
    "\"DSG\"",
    "\"DSI\"",
    "\"DTM\"",
    "\"EFI\"",
    "\"ELM\"",
    "\"ELU\"",
    "\"EMP\"",
    "\"EQA\"",
    "\"EQD\"",
    "\"EQN\"",
    "\"ERC\"",
    "\"ERP\"",
    "\"FCA\"",
    "\"FII\"",
    "\"FNS\"",
    "\"FNT\"",
    "\"FTX\"",
    "\"GDS\"",
    "\"GID\"",
    "\"GIN\"",
    "\"GIR\"",
    "\"GIS\"",
    "\"GOR\"",
    "\"GRU\"",
    "\"HAN\"",
    "\"HYN\"",
    "\"ICD\"",
    "\"IDE\"",
    "\"IHC\"",
    "\"IMD\"",
    "\"IND\"",
    "\"INP\"",
    "\"INV\"",
    "\"IRQ\"",
    "\"LAN\"",
    "\"LIN\"",
    "\"LOC\"",
    "\"MEA\"",
    "\"MEM\"",
    "\"MKS\"",
    "\"MOA\"",
    "\"MSG\"",
    "\"NAD\"",
    "\"NAT\"",
    "\"PAC\"",
    "\"PAI\"",
    "\"PAS\"",
    "\"PAT\"",
    "\"PCD\"",
    "\"PCI\"",
    "\"PDI\"",
    "\"PGI\"",
    "\"PIA\"",
    "\"PIT\"",
    "\"PNA\"",
    "\"PRC\"",
    "\"PRI\"",
    "\"PSD\"",
    "\"PTY\"",
    "\"QTY\"",
    "\"QUA\"",
    "\"QVR\"",
    "\"RCS\"",
    "\"REL\"",
    "\"RFF\"",
    "\"RNG\"",
    "\"RSL\"",
    "\"RTE\"",
    "\"SAL\"",
    "\"SCC\"",
    "\"SCD\"",
    "\"SEG\"",
    "\"SEL\"",
    "\"SEQ\"",
    "\"SFI\"",
    "\"SGP\"",
    "\"SGU\"",
    "\"SPR\"",
    "\"SPS\"",
    "\"STA\"",
    "\"STC\"",
    "\"STG\"",
    "\"STS\"",
    "\"TAX\"",
    "\"TCC\"",
    "\"TDT\"",
    "\"TEM\"",
    "\"TMD\"",
    "\"TMP\"",
    "\"TOD\"",
    "\"TPL\"",
    "\"TRU\"",
    "\"TSR\"",
    "\"VLI\"",
    "\"UCD\"",
    "\"UCF\"",
    "\"UCI\"",
    "\"UCM\"",
    "\"UCS\"",
    "\"UGH\"",
    "\"UGT\"",
    "\"UIB\"",
    "\"UIH\"",
    "\"UIR\"",
    "\"UIT\"",
    "\"UIZ\"",
    "\"UNB\"",
    "\"UNE\"",
    "\"UNG\"",
    "\"UNH\"",
    "\"UNO\"",
    "\"UNP\"",
    "\"UNS\"",
    "\"UNT\"",
    "\"UNZ\"",
    "\"USA\"",
    "\"USB\"",
    "\"USC\"",
    "\"USD\"",
    "\"USE\"",
    "\"USF\"",
    "\"USH\"",
    "\"USL\"",
    "\"USR\"",
    "\"UST\"",
    "\"USU\"",
    "\"USX\"",
    "\"USY\"",
    "<DATA>",
    "<NUMBER>",
    "\"\\\'\"",
    "\"+\"",
    "\":\"",
    "\"*\"",
  };

}
