/* Generated By:JavaCC: Do not edit this line. D99BConstants.java */
package com.appliedmodels.edifact.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface D99BConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADR = 6;
  /** RegularExpression Id. */
  int AGR = 7;
  /** RegularExpression Id. */
  int AJT = 8;
  /** RegularExpression Id. */
  int ALC = 9;
  /** RegularExpression Id. */
  int ALI = 10;
  /** RegularExpression Id. */
  int APR = 11;
  /** RegularExpression Id. */
  int ARD = 12;
  /** RegularExpression Id. */
  int ARR = 13;
  /** RegularExpression Id. */
  int ASI = 14;
  /** RegularExpression Id. */
  int ATT = 15;
  /** RegularExpression Id. */
  int AUT = 16;
  /** RegularExpression Id. */
  int BGM = 17;
  /** RegularExpression Id. */
  int BII = 18;
  /** RegularExpression Id. */
  int BUS = 19;
  /** RegularExpression Id. */
  int CAV = 20;
  /** RegularExpression Id. */
  int CCD = 21;
  /** RegularExpression Id. */
  int CCI = 22;
  /** RegularExpression Id. */
  int CDI = 23;
  /** RegularExpression Id. */
  int CDS = 24;
  /** RegularExpression Id. */
  int CDV = 25;
  /** RegularExpression Id. */
  int CED = 26;
  /** RegularExpression Id. */
  int CIN = 27;
  /** RegularExpression Id. */
  int CLI = 28;
  /** RegularExpression Id. */
  int CMP = 29;
  /** RegularExpression Id. */
  int CNI = 30;
  /** RegularExpression Id. */
  int CNT = 31;
  /** RegularExpression Id. */
  int COD = 32;
  /** RegularExpression Id. */
  int COM = 33;
  /** RegularExpression Id. */
  int COT = 34;
  /** RegularExpression Id. */
  int CPI = 35;
  /** RegularExpression Id. */
  int CPS = 36;
  /** RegularExpression Id. */
  int CPT = 37;
  /** RegularExpression Id. */
  int CST = 38;
  /** RegularExpression Id. */
  int CTA = 39;
  /** RegularExpression Id. */
  int CUX = 40;
  /** RegularExpression Id. */
  int DAM = 41;
  /** RegularExpression Id. */
  int DFN = 42;
  /** RegularExpression Id. */
  int DGS = 43;
  /** RegularExpression Id. */
  int DII = 44;
  /** RegularExpression Id. */
  int DIM = 45;
  /** RegularExpression Id. */
  int DLI = 46;
  /** RegularExpression Id. */
  int DLM = 47;
  /** RegularExpression Id. */
  int DMS = 48;
  /** RegularExpression Id. */
  int DOC = 49;
  /** RegularExpression Id. */
  int DRD = 50;
  /** RegularExpression Id. */
  int DSG = 51;
  /** RegularExpression Id. */
  int DSI = 52;
  /** RegularExpression Id. */
  int DTM = 53;
  /** RegularExpression Id. */
  int EDT = 54;
  /** RegularExpression Id. */
  int EFI = 55;
  /** RegularExpression Id. */
  int ELM = 56;
  /** RegularExpression Id. */
  int ELU = 57;
  /** RegularExpression Id. */
  int ELV = 58;
  /** RegularExpression Id. */
  int EMP = 59;
  /** RegularExpression Id. */
  int EQA = 60;
  /** RegularExpression Id. */
  int EQD = 61;
  /** RegularExpression Id. */
  int EQN = 62;
  /** RegularExpression Id. */
  int ERC = 63;
  /** RegularExpression Id. */
  int ERP = 64;
  /** RegularExpression Id. */
  int EVE = 65;
  /** RegularExpression Id. */
  int EVT = 66;
  /** RegularExpression Id. */
  int FCA = 67;
  /** RegularExpression Id. */
  int FII = 68;
  /** RegularExpression Id. */
  int FNS = 69;
  /** RegularExpression Id. */
  int FNT = 70;
  /** RegularExpression Id. */
  int FOR = 71;
  /** RegularExpression Id. */
  int FSQ = 72;
  /** RegularExpression Id. */
  int FTX = 73;
  /** RegularExpression Id. */
  int GDS = 74;
  /** RegularExpression Id. */
  int GEI = 75;
  /** RegularExpression Id. */
  int GID = 76;
  /** RegularExpression Id. */
  int GIN = 77;
  /** RegularExpression Id. */
  int GIR = 78;
  /** RegularExpression Id. */
  int GIS = 79;
  /** RegularExpression Id. */
  int GOR = 80;
  /** RegularExpression Id. */
  int GRU = 81;
  /** RegularExpression Id. */
  int HAN = 82;
  /** RegularExpression Id. */
  int HYN = 83;
  /** RegularExpression Id. */
  int ICD = 84;
  /** RegularExpression Id. */
  int IDE = 85;
  /** RegularExpression Id. */
  int IFD = 86;
  /** RegularExpression Id. */
  int IHC = 87;
  /** RegularExpression Id. */
  int IMD = 88;
  /** RegularExpression Id. */
  int IND = 89;
  /** RegularExpression Id. */
  int INP = 90;
  /** RegularExpression Id. */
  int INV = 91;
  /** RegularExpression Id. */
  int IRQ = 92;
  /** RegularExpression Id. */
  int LAN = 93;
  /** RegularExpression Id. */
  int LIN = 94;
  /** RegularExpression Id. */
  int LOC = 95;
  /** RegularExpression Id. */
  int MEA = 96;
  /** RegularExpression Id. */
  int MEM = 97;
  /** RegularExpression Id. */
  int MKS = 98;
  /** RegularExpression Id. */
  int MOA = 99;
  /** RegularExpression Id. */
  int MSG = 100;
  /** RegularExpression Id. */
  int NAD = 101;
  /** RegularExpression Id. */
  int NAT = 102;
  /** RegularExpression Id. */
  int PAC = 103;
  /** RegularExpression Id. */
  int PAI = 104;
  /** RegularExpression Id. */
  int PAS = 105;
  /** RegularExpression Id. */
  int PAT = 106;
  /** RegularExpression Id. */
  int PCC = 107;
  /** RegularExpression Id. */
  int PCD = 108;
  /** RegularExpression Id. */
  int PCI = 109;
  /** RegularExpression Id. */
  int PDI = 110;
  /** RegularExpression Id. */
  int PGI = 111;
  /** RegularExpression Id. */
  int PIA = 112;
  /** RegularExpression Id. */
  int PNA = 113;
  /** RegularExpression Id. */
  int POC = 114;
  /** RegularExpression Id. */
  int PRC = 115;
  /** RegularExpression Id. */
  int PRI = 116;
  /** RegularExpression Id. */
  int PSD = 117;
  /** RegularExpression Id. */
  int PTY = 118;
  /** RegularExpression Id. */
  int PYT = 119;
  /** RegularExpression Id. */
  int QRS = 120;
  /** RegularExpression Id. */
  int QTY = 121;
  /** RegularExpression Id. */
  int QUA = 122;
  /** RegularExpression Id. */
  int QVR = 123;
  /** RegularExpression Id. */
  int RCS = 124;
  /** RegularExpression Id. */
  int REL = 125;
  /** RegularExpression Id. */
  int RFF = 126;
  /** RegularExpression Id. */
  int RJL = 127;
  /** RegularExpression Id. */
  int RNG = 128;
  /** RegularExpression Id. */
  int ROD = 129;
  /** RegularExpression Id. */
  int RSL = 130;
  /** RegularExpression Id. */
  int RTE = 131;
  /** RegularExpression Id. */
  int SAL = 132;
  /** RegularExpression Id. */
  int SCC = 133;
  /** RegularExpression Id. */
  int SCD = 134;
  /** RegularExpression Id. */
  int SEG = 135;
  /** RegularExpression Id. */
  int SEL = 136;
  /** RegularExpression Id. */
  int SEQ = 137;
  /** RegularExpression Id. */
  int SFI = 138;
  /** RegularExpression Id. */
  int SGP = 139;
  /** RegularExpression Id. */
  int SGU = 140;
  /** RegularExpression Id. */
  int SPR = 141;
  /** RegularExpression Id. */
  int SPS = 142;
  /** RegularExpression Id. */
  int STA = 143;
  /** RegularExpression Id. */
  int STC = 144;
  /** RegularExpression Id. */
  int STG = 145;
  /** RegularExpression Id. */
  int STS = 146;
  /** RegularExpression Id. */
  int TAX = 147;
  /** RegularExpression Id. */
  int TCC = 148;
  /** RegularExpression Id. */
  int TDT = 149;
  /** RegularExpression Id. */
  int TEM = 150;
  /** RegularExpression Id. */
  int TMD = 151;
  /** RegularExpression Id. */
  int TMP = 152;
  /** RegularExpression Id. */
  int TOD = 153;
  /** RegularExpression Id. */
  int TPL = 154;
  /** RegularExpression Id. */
  int TRU = 155;
  /** RegularExpression Id. */
  int TSR = 156;
  /** RegularExpression Id. */
  int VLI = 157;
  /** RegularExpression Id. */
  int UCD = 158;
  /** RegularExpression Id. */
  int UCF = 159;
  /** RegularExpression Id. */
  int UCI = 160;
  /** RegularExpression Id. */
  int UCM = 161;
  /** RegularExpression Id. */
  int UCS = 162;
  /** RegularExpression Id. */
  int UGH = 163;
  /** RegularExpression Id. */
  int UGT = 164;
  /** RegularExpression Id. */
  int UIB = 165;
  /** RegularExpression Id. */
  int UIH = 166;
  /** RegularExpression Id. */
  int UIR = 167;
  /** RegularExpression Id. */
  int UIT = 168;
  /** RegularExpression Id. */
  int UIZ = 169;
  /** RegularExpression Id. */
  int UNB = 170;
  /** RegularExpression Id. */
  int UNE = 171;
  /** RegularExpression Id. */
  int UNG = 172;
  /** RegularExpression Id. */
  int UNH = 173;
  /** RegularExpression Id. */
  int UNO = 174;
  /** RegularExpression Id. */
  int UNP = 175;
  /** RegularExpression Id. */
  int UNS = 176;
  /** RegularExpression Id. */
  int UNT = 177;
  /** RegularExpression Id. */
  int UNZ = 178;
  /** RegularExpression Id. */
  int USA = 179;
  /** RegularExpression Id. */
  int USB = 180;
  /** RegularExpression Id. */
  int USC = 181;
  /** RegularExpression Id. */
  int USD = 182;
  /** RegularExpression Id. */
  int USE = 183;
  /** RegularExpression Id. */
  int USF = 184;
  /** RegularExpression Id. */
  int USH = 185;
  /** RegularExpression Id. */
  int USL = 186;
  /** RegularExpression Id. */
  int USR = 187;
  /** RegularExpression Id. */
  int UST = 188;
  /** RegularExpression Id. */
  int USU = 189;
  /** RegularExpression Id. */
  int USX = 190;
  /** RegularExpression Id. */
  int USY = 191;
  /** RegularExpression Id. */
  int AAI = 192;
  /** RegularExpression Id. */
  int ADI = 193;
  /** RegularExpression Id. */
  int ADS = 194;
  /** RegularExpression Id. */
  int ALS = 195;
  /** RegularExpression Id. */
  int APD = 196;
  /** RegularExpression Id. */
  int ASD = 197;
  /** RegularExpression Id. */
  int ATI = 198;
  /** RegularExpression Id. */
  int ATR = 199;
  /** RegularExpression Id. */
  int BLI = 200;
  /** RegularExpression Id. */
  int CLT = 201;
  /** RegularExpression Id. */
  int CMN = 202;
  /** RegularExpression Id. */
  int CNX = 203;
  /** RegularExpression Id. */
  int CON = 204;
  /** RegularExpression Id. */
  int CRI = 205;
  /** RegularExpression Id. */
  int CUR = 206;
  /** RegularExpression Id. */
  int DAV = 207;
  /** RegularExpression Id. */
  int DIS = 208;
  /** RegularExpression Id. */
  int DNT = 209;
  /** RegularExpression Id. */
  int DTI = 210;
  /** RegularExpression Id. */
  int ERI = 211;
  /** RegularExpression Id. */
  int FRM = 212;
  /** RegularExpression Id. */
  int FTI = 213;
  /** RegularExpression Id. */
  int HDI = 214;
  /** RegularExpression Id. */
  int ICI = 215;
  /** RegularExpression Id. */
  int IFT = 216;
  /** RegularExpression Id. */
  int ITC = 217;
  /** RegularExpression Id. */
  int ITD = 218;
  /** RegularExpression Id. */
  int ITM = 219;
  /** RegularExpression Id. */
  int LKP = 220;
  /** RegularExpression Id. */
  int MAP = 221;
  /** RegularExpression Id. */
  int MOV = 222;
  /** RegularExpression Id. */
  int MSD = 223;
  /** RegularExpression Id. */
  int NAA = 224;
  /** RegularExpression Id. */
  int NAM = 225;
  /** RegularExpression Id. */
  int NME = 226;
  /** RegularExpression Id. */
  int NUN = 227;
  /** RegularExpression Id. */
  int ODI = 228;
  /** RegularExpression Id. */
  int ODS = 229;
  /** RegularExpression Id. */
  int ORG = 230;
  /** RegularExpression Id. */
  int OTI = 231;
  /** RegularExpression Id. */
  int PDT = 232;
  /** RegularExpression Id. */
  int PLI = 233;
  /** RegularExpression Id. */
  int PMT = 234;
  /** RegularExpression Id. */
  int POS = 235;
  /** RegularExpression Id. */
  int PRD = 236;
  /** RegularExpression Id. */
  int PRE = 237;
  /** RegularExpression Id. */
  int PRO = 238;
  /** RegularExpression Id. */
  int PRT = 239;
  /** RegularExpression Id. */
  int PSI = 240;
  /** RegularExpression Id. */
  int RCI = 241;
  /** RegularExpression Id. */
  int RPI = 242;
  /** RegularExpression Id. */
  int RTC = 243;
  /** RegularExpression Id. */
  int RTI = 244;
  /** RegularExpression Id. */
  int RUL = 245;
  /** RegularExpression Id. */
  int SDT = 246;
  /** RegularExpression Id. */
  int SSR = 247;
  /** RegularExpression Id. */
  int TDI = 248;
  /** RegularExpression Id. */
  int TFF = 249;
  /** RegularExpression Id. */
  int TIF = 250;
  /** RegularExpression Id. */
  int TRF = 251;
  /** RegularExpression Id. */
  int TVL = 252;
  /** RegularExpression Id. */
  int TXS = 253;
  /** RegularExpression Id. */
  int VEH = 254;
  /** RegularExpression Id. */
  int DATA = 255;
  /** RegularExpression Id. */
  int NUMBER = 256;
  /** RegularExpression Id. */
  int SEGTERM = 257;
  /** RegularExpression Id. */
  int DATASEP = 258;
  /** RegularExpression Id. */
  int COMPDATASEP = 259;
  /** RegularExpression Id. */
  int REPEATSEP = 260;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"ADR\"",
    "\"AGR\"",
    "\"AJT\"",
    "\"ALC\"",
    "\"ALI\"",
    "\"APR\"",
    "\"ARD\"",
    "\"ARR\"",
    "\"ASI\"",
    "\"ATT\"",
    "\"AUT\"",
    "\"BGM\"",
    "\"BII\"",
    "\"BUS\"",
    "\"CAV\"",
    "\"CCD\"",
    "\"CCI\"",
    "\"CDI\"",
    "\"CDS\"",
    "\"CDV\"",
    "\"CED\"",
    "\"CIN\"",
    "\"CLI\"",
    "\"CMP\"",
    "\"CNI\"",
    "\"CNT\"",
    "\"COD\"",
    "\"COM\"",
    "\"COT\"",
    "\"CPI\"",
    "\"CPS\"",
    "\"CPT\"",
    "\"CST\"",
    "\"CTA\"",
    "\"CUX\"",
    "\"DAM\"",
    "\"DFN\"",
    "\"DGS\"",
    "\"DII\"",
    "\"DIM\"",
    "\"DLI\"",
    "\"DLM\"",
    "\"DMS\"",
    "\"DOC\"",
    "\"DRD\"",
    "\"DSG\"",
    "\"DSI\"",
    "\"DTM\"",
    "\"EDT\"",
    "\"EFI\"",
    "\"ELM\"",
    "\"ELU\"",
    "\"ELV\"",
    "\"EMP\"",
    "\"EQA\"",
    "\"EQD\"",
    "\"EQN\"",
    "\"ERC\"",
    "\"ERP\"",
    "\"EVE\"",
    "\"EVT\"",
    "\"FCA\"",
    "\"FII\"",
    "\"FNS\"",
    "\"FNT\"",
    "\"FOR\"",
    "\"FSQ\"",
    "\"FTX\"",
    "\"GDS\"",
    "\"GEI\"",
    "\"GID\"",
    "\"GIN\"",
    "\"GIR\"",
    "\"GIS\"",
    "\"GOR\"",
    "\"GRU\"",
    "\"HAN\"",
    "\"HYN\"",
    "\"ICD\"",
    "\"IDE\"",
    "\"IFD\"",
    "\"IHC\"",
    "\"IMD\"",
    "\"IND\"",
    "\"INP\"",
    "\"INV\"",
    "\"IRQ\"",
    "\"LAN\"",
    "\"LIN\"",
    "\"LOC\"",
    "\"MEA\"",
    "\"MEM\"",
    "\"MKS\"",
    "\"MOA\"",
    "\"MSG\"",
    "\"NAD\"",
    "\"NAT\"",
    "\"PAC\"",
    "\"PAI\"",
    "\"PAS\"",
    "\"PAT\"",
    "\"PCC\"",
    "\"PCD\"",
    "\"PCI\"",
    "\"PDI\"",
    "\"PGI\"",
    "\"PIA\"",
    "\"PNA\"",
    "\"POC\"",
    "\"PRC\"",
    "\"PRI\"",
    "\"PSD\"",
    "\"PTY\"",
    "\"PYT\"",
    "\"QRS\"",
    "\"QTY\"",
    "\"QUA\"",
    "\"QVR\"",
    "\"RCS\"",
    "\"REL\"",
    "\"RFF\"",
    "\"RJL\"",
    "\"RNG\"",
    "\"ROD\"",
    "\"RSL\"",
    "\"RTE\"",
    "\"SAL\"",
    "\"SCC\"",
    "\"SCD\"",
    "\"SEG\"",
    "\"SEL\"",
    "\"SEQ\"",
    "\"SFI\"",
    "\"SGP\"",
    "\"SGU\"",
    "\"SPR\"",
    "\"SPS\"",
    "\"STA\"",
    "\"STC\"",
    "\"STG\"",
    "\"STS\"",
    "\"TAX\"",
    "\"TCC\"",
    "\"TDT\"",
    "\"TEM\"",
    "\"TMD\"",
    "\"TMP\"",
    "\"TOD\"",
    "\"TPL\"",
    "\"TRU\"",
    "\"TSR\"",
    "\"VLI\"",
    "\"UCD\"",
    "\"UCF\"",
    "\"UCI\"",
    "\"UCM\"",
    "\"UCS\"",
    "\"UGH\"",
    "\"UGT\"",
    "\"UIB\"",
    "\"UIH\"",
    "\"UIR\"",
    "\"UIT\"",
    "\"UIZ\"",
    "\"UNB\"",
    "\"UNE\"",
    "\"UNG\"",
    "\"UNH\"",
    "\"UNO\"",
    "\"UNP\"",
    "\"UNS\"",
    "\"UNT\"",
    "\"UNZ\"",
    "\"USA\"",
    "\"USB\"",
    "\"USC\"",
    "\"USD\"",
    "\"USE\"",
    "\"USF\"",
    "\"USH\"",
    "\"USL\"",
    "\"USR\"",
    "\"UST\"",
    "\"USU\"",
    "\"USX\"",
    "\"USY\"",
    "\"AAI\"",
    "\"ADI\"",
    "\"ADS\"",
    "\"ALS\"",
    "\"APD\"",
    "\"ASD\"",
    "\"ATI\"",
    "\"ATR\"",
    "\"BLI\"",
    "\"CLT\"",
    "\"CMN\"",
    "\"CNX\"",
    "\"CON\"",
    "\"CRI\"",
    "\"CUR\"",
    "\"DAV\"",
    "\"DIS\"",
    "\"DNT\"",
    "\"DTI\"",
    "\"ERI\"",
    "\"FRM\"",
    "\"FTI\"",
    "\"HDI\"",
    "\"ICI\"",
    "\"IFT\"",
    "\"ITC\"",
    "\"ITD\"",
    "\"ITM\"",
    "\"LKP\"",
    "\"MAP\"",
    "\"MOV\"",
    "\"MSD\"",
    "\"NAA\"",
    "\"NAM\"",
    "\"NME\"",
    "\"NUN\"",
    "\"ODI\"",
    "\"ODS\"",
    "\"ORG\"",
    "\"OTI\"",
    "\"PDT\"",
    "\"PLI\"",
    "\"PMT\"",
    "\"POS\"",
    "\"PRD\"",
    "\"PRE\"",
    "\"PRO\"",
    "\"PRT\"",
    "\"PSI\"",
    "\"RCI\"",
    "\"RPI\"",
    "\"RTC\"",
    "\"RTI\"",
    "\"RUL\"",
    "\"SDT\"",
    "\"SSR\"",
    "\"TDI\"",
    "\"TFF\"",
    "\"TIF\"",
    "\"TRF\"",
    "\"TVL\"",
    "\"TXS\"",
    "\"VEH\"",
    "<DATA>",
    "<NUMBER>",
    "\"\\\'\"",
    "\"+\"",
    "\":\"",
    "\"*\"",
  };

}
