/* Generated By:JavaCC: Do not edit this line. S401Constants.java */
package com.appliedmodels.edifact.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface S401Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int UCD = 6;
  /** RegularExpression Id. */
  int UCF = 7;
  /** RegularExpression Id. */
  int UCI = 8;
  /** RegularExpression Id. */
  int UCM = 9;
  /** RegularExpression Id. */
  int UCS = 10;
  /** RegularExpression Id. */
  int UGH = 11;
  /** RegularExpression Id. */
  int UGT = 12;
  /** RegularExpression Id. */
  int UIB = 13;
  /** RegularExpression Id. */
  int UIH = 14;
  /** RegularExpression Id. */
  int UIR = 15;
  /** RegularExpression Id. */
  int UIT = 16;
  /** RegularExpression Id. */
  int UIZ = 17;
  /** RegularExpression Id. */
  int UNB = 18;
  /** RegularExpression Id. */
  int UNE = 19;
  /** RegularExpression Id. */
  int UNG = 20;
  /** RegularExpression Id. */
  int UNH = 21;
  /** RegularExpression Id. */
  int UNO = 22;
  /** RegularExpression Id. */
  int UNP = 23;
  /** RegularExpression Id. */
  int UNS = 24;
  /** RegularExpression Id. */
  int UNT = 25;
  /** RegularExpression Id. */
  int UNZ = 26;
  /** RegularExpression Id. */
  int USA = 27;
  /** RegularExpression Id. */
  int USB = 28;
  /** RegularExpression Id. */
  int USC = 29;
  /** RegularExpression Id. */
  int USD = 30;
  /** RegularExpression Id. */
  int USE = 31;
  /** RegularExpression Id. */
  int USF = 32;
  /** RegularExpression Id. */
  int USH = 33;
  /** RegularExpression Id. */
  int USL = 34;
  /** RegularExpression Id. */
  int USR = 35;
  /** RegularExpression Id. */
  int UST = 36;
  /** RegularExpression Id. */
  int USU = 37;
  /** RegularExpression Id. */
  int USX = 38;
  /** RegularExpression Id. */
  int USY = 39;
  /** RegularExpression Id. */
  int DATA = 40;
  /** RegularExpression Id. */
  int NUMBER = 41;
  /** RegularExpression Id. */
  int SEGTERM = 42;
  /** RegularExpression Id. */
  int DATASEP = 43;
  /** RegularExpression Id. */
  int COMPDATASEP = 44;
  /** RegularExpression Id. */
  int REPEATSEP = 45;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"UCD\"",
    "\"UCF\"",
    "\"UCI\"",
    "\"UCM\"",
    "\"UCS\"",
    "\"UGH\"",
    "\"UGT\"",
    "\"UIB\"",
    "\"UIH\"",
    "\"UIR\"",
    "\"UIT\"",
    "\"UIZ\"",
    "\"UNB\"",
    "\"UNE\"",
    "\"UNG\"",
    "\"UNH\"",
    "\"UNO\"",
    "\"UNP\"",
    "\"UNS\"",
    "\"UNT\"",
    "\"UNZ\"",
    "\"USA\"",
    "\"USB\"",
    "\"USC\"",
    "\"USD\"",
    "\"USE\"",
    "\"USF\"",
    "\"USH\"",
    "\"USL\"",
    "\"USR\"",
    "\"UST\"",
    "\"USU\"",
    "\"USX\"",
    "\"USY\"",
    "<DATA>",
    "<NUMBER>",
    "\"\\\'\"",
    "\"+\"",
    "\":\"",
    "\"*\"",
  };

}
